### ISSUE TITLE
Register for XML filetype during installation

### ISSUE THREAD

**Issue by stevebow** [microsoft/XmlNotepad#101]
After XML Notepad has been installed, it does not appear in the list of programs to choose from when opening an XML file via “Open with…”.  While you can of course add XML Notepad manually, it would be convenient if it were available when installed.  Especially for the ClickOnce version, as it is installed in an obscure location making it difficult to find to add manually.

**Comment by lovettchris** [comment]
Yes, I think this can be done also in the standalone installer and by first launch of the app after clickonce install.

**Comment by lovettchris** [comment]
I changed XmlNotepad.exe so that when you run it it self-registers the .xml file type association - this way it will work no matter which installer you use to install it.
