### ISSUE TITLE
Possibility to install at a custom location

### ISSUE THREAD

**Issue by stevebow** [microsoft/XmlNotepad#102]
A request to allow the possibility to install the Standalone version at a custom location of the user's choice please.  I prefer to install programs on a separate partition to C: and this is currently not possible as the installer offers no choice.

**Comment by lovettchris** [comment]
Fixed in 2.8.0.46.

**Comment by stevebow** [comment]
Chris, could I confirm the version this was fixed in please?  I do have 2.8.0.46 (standalone) installed.  I uninstalled this, then ran the installer again.  There is no option to select an install location, only to accept the license and an Install button below this.  When I click Install, XN is simply installed back to C:\Program Files (x86)\LovettSoftware\.  Is there something I've missed?

**Comment by lovettchris** [comment]
Right, sorry, I was too lazy to post a new release so I replaced the zip file in the 2.8.0.46 release, did you re-download the XmlNotepadSetup.zip, unzipt it and run the new XmlNotepadSetup.msi?  It should have a 9/15 "Creation" date on the file and the installer should now present this page:
![image](https://user-images.githubusercontent.com/18707114/133670729-7ed9b982-a2bf-41c5-b348-833c9ffcb990.png)

**Comment by stevebow** [comment]
I downloaded Standalone 2.8.0.46 from the usual location I have used (https://microsoft.github.io/XmlNotepad/#install/) and found it to be the "old" package, perhaps this needs to be replaced by the "new" package I downloaded at https://github.com/microsoft/XmlNotepad/releases ?

The "new" version was installed at the location of my choice and seems to work fine from there, thanks!  Just a few minor "would be nice" points:
- The install location is not displayed in Programs and Features in the Location column.
- The copyright notice in the About window is 2006(!).  I guess this should be 2021 or at least 2006-2021?
- An option during install to add an item in the Start menu.

**Comment by lovettchris** [comment]
Thanks for trying it out and for reporting the additional bugs.
(1) not sure how to do this or if it is even visible in windows 11 revamped (simpler) dialogs
(2) will fix in the next release.
(3) it is in the start menu under "Lovett Software".

**Comment by lovettchris** [comment]
The copyright is fixed in version 2.8.0.53 :

![image](https://user-images.githubusercontent.com/18707114/158003163-63fe95b7-42a5-4b52-a95e-789dbdbb25f4.png)

**Comment by lovettchris** [comment]
Resolving this as closed for now, the issue about showing program location in "add remove programs" dialog is now moot given that windows 11 doesn't show any of this detail any more:

![image](https://user-images.githubusercontent.com/18707114/158003226-e7e89ee7-e63a-4fc3-b89b-f93ca8da3f69.png)

**Comment by stevebow** [comment]
Thanks for the recent update Chris.

Windows 10 Settings->Apps & Features also presents a limited view of installed apps:

![image](https://user-images.githubusercontent.com/20422753/158004953-28ef7b67-1c34-4854-b243-f8bf8bee931e.png)

But what I was referring to was the information presented in Control Panel->All Control Panel Items->Programs and Features:

![image](https://user-images.githubusercontent.com/20422753/158004984-e2e5e49c-fb58-4bff-bd60-d376de6b879f.png)

I don't know if Control Panel has been removed in Win 11, but in any case Win 10 has plenty of life in it still and I'd perhaps ask you to reconsider.

Thanks,
Steve

**Comment by lovettchris** [comment]
I see, thanks, i found you can still manually run "appwiz.cpl" to get that view, and the location is still missing on windows 11.  No idea how to fix that.  I'm using the [Wix Toolset](https://wixtoolset.org/) to build that installer but I'm not an MSI Schema expert...

**Comment by stevebow** [comment]
I am certainly no installer expert either.  Perhaps contacting the WiX support pople at [https://www.firegiant.com/](url) may help?

**Comment by lovettchris** [comment]
Ok, I filed this issue: https://github.com/wixtoolset/issues/issues/6741
We'll see what they say.

**Comment by lovettchris** [comment]
Found the solution:
```xml
<SetProperty Id="ARPINSTALLLOCATION" Value="[APPINSTALLROOTDIR]" After="CostFinalize" />
```

This fix will be in the next release.
