### ISSUE TITLE
Unable to see XSL Output

### ISSUE THREAD

**Issue by Rene61** [microsoft/XmlNotepad#103]
Since upgrading to 2.8.0.35, nothing appears in XSL Output.  I've tried to uninstall and reinstall but nothing.

**Comment by lovettchris** [comment]
Hmmm, that's not good, can you try installing this: https://developer.microsoft.com/en-us/microsoft-edge/webview2/. I recently switched over to webview2 to fix performance problems with the old embedded browser component.

**Comment by Rene61** [comment]
That did the trick.

**Comment by lovettchris** [comment]
Great thanks, I think I also fixed the bug you found in 2.8.0.36.
