### ISSUE TITLE
Error Transforming XML

### ISSUE THREAD

**Issue by Rene61** [microsoft/XmlNotepad#106]
Using 2.8.0.36.  When attempting to open a 309K XML file (see attached), I get the following error message:

Error Transforming XML
Value does not fall within the expected range.

[MTIResponse-MillTestComplex1b-Test.txt](https://github.com/microsoft/XmlNotepad/files/6816654/MTIResponse-MillTestComplex1b-Test.txt)

Thanks!

**Comment by lovettchris** [comment]
Fixed in 2.8.0.38.
