### ISSUE TITLE
Download link from Microsoft site

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#107]
I searched at MS-site for "XPS Viewer"
https://www.microsoft.com/en-us/download/search.aspx?q=xps+viewer&first=11
and on second page I found "XML Notepad" - nice description, but dead link ...

**Comment by lovettchris** [comment]
Thanks, you wouldn't believe how hard it is to change anything on www.microsoft.com.  I'm just happy they are no longer distributing XML notepad 2007 :-)

**Comment by Jaiganeshkumaran** [comment]
Maybe publish the MSIX version to the Store since the search results also seem to include Store apps.

**Comment by lovettchris** [comment]
Seems to be gone now, finally.
