### ISSUE TITLE
doubleclick on a file with blanks in its name

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#108]
Happened both with 2.8.035 and 2.8.038

I have defined my Win 10 to open XML Notepad with a doubleclick on a XML file. Usually no problem, but sometimes Win is asking which program I want to use with XML (or with PDF or TXT or ...)
Now I doubleclick on file "d:\a b c.xml", and I get
![grafik](https://user-images.githubusercontent.com/13277944/125801582-c5cdf2d6-65d3-47bb-ac69-57a02170d059.png)
I press "OK" and get
![grafik](https://user-images.githubusercontent.com/13277944/125801841-b4731d53-f5dd-4bf7-b23e-94fb9d1beecb.png)
I press "OK" and
- my text editor opens the (non exisiting file "D:\a") 
- and I get:
![grafik](https://user-images.githubusercontent.com/13277944/125802139-8eb05088-9c63-4a9a-8809-a95898f531b5.png)

and so on ...

It is OK when ..
- I use "right mouse - open with" or
- doubleclick on a file(path) without blanks or
- use "File - open "

Something wrong with ...?

**Comment by lovettchris** [comment]
I cannot reproduce this on a clean machine, but you might have some old broken registry entries for previous versions of XML notepad, depending on how you have installed it in the past.  These steps might help:

1. run the **regedit** program (comes with windows)
2. goto "Computer\HKEY_CLASSES_ROOT\.xml\OpenWithProgids" and remove any "XmlNotepad.xmlfile" entry there.
3. goto "Computer\HKEY_CLASSES_ROOT\XmlNotepad.xmlfile" and remove it if it exists.
4. goto "Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\.xml\OpenWithProgids" and remove any "XmlNotepad.xmlfile" entry there.
5. goto "Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\XmlNotepad.xmlfile" and remove it if it exists.
6. goto "Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.xml" and delete **UserChoice** if it exists.

Now re-start your XML Notepad 2.8.038.  It will automatically re-register the above information correctly.  Now repeat making XML notepad your default application for opening XML files  (and you should not need to use "Look for another app on this PC" for this, the installed XML notepad should show up in this list).

Now try double click test again.

**Comment by lovettchris** [comment]
Oh and one more thing, problems with blanks in the name is usually caused by missing double quotes around the %1 argument in the registry entry for `XmlNotepad.xmlfile`.  But XML notepad has registered this with `"%1"` for a while now, and when windows creates this entry for the user because the user used "Look for another app on this PC" then it too also puts double quotes around the `"%1"`.  But if you find a registry entry for `XmlNotepad.xmlfile` that does has `%1` instead of `"%1"`, then add the quotes and you should be good.  No need to reboot or anything, the windows explorer always checks the latest registry values.

**Comment by Pierre-de-la-Verre** [comment]
Thanks Chris

I used "FileTypesMan" from Nirsoft to check and modify the extensions. I had entries from August 2020 without quotes, fixed it and the handling of spaces is OK now.

Nevertheless it was asking again and again "Which software should be opened?". Then I made the regedit-jobs, and it looks OK now.

**Comment by lovettchris** [comment]
Great, and I double checked that the current version of XML notepad does put the double quotes around the registry entry as you can see [here](https://github.com/microsoft/XmlNotepad/blob/d6eeb76f81c65b7131b7bdb786c94ccada760b96/src/Model/FileAssociation.cs).
