### ISSUE TITLE
"Help" menu: Index and Contents

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#109]
"Index" and "Contents" show the same HTML. Is it intended?

**Comment by lovettchris** [comment]
Yeah, it was a left over from previous .chm help file which really did have a help index.  So the index option will be removed in the next update.

**Comment by lovettchris** [comment]
Fixed in 2.8.0.40

**Comment by Pierre-de-la-Verre** [comment]
Fixed in 2.8.0.40
