### ISSUE TITLE
Cannot compile because of resx error MSB3103

### ISSUE THREAD

**Issue by TFreudi1** [microsoft/XmlNotepad#110]
I got to errors when I compile current branch with current VS2019 16.10.4 :
error MSB3103: Ungültige ResX-Datei. Der angeforderte Wert "Ctrl" konnte nicht gefunden werden. Zeile 260, Position 5.
error MSB3103: Ungültige ResX-Datei. Der angeforderte Wert "Ctrl" konnte nicht gefunden werden. Zeile 227, Position 5.

Any hint wht's wrong ?
I just checkout and open it in VS2019, try to run Application-project

**Comment by lovettchris** [comment]
"error MSB3103: Invalid ResX file. The requested value "Ctrl" could not be found. Line 260, item 5."

Can you also provide the file name where the compile error occurs?  You can see my [github action ](https://github.com/microsoft/XmlNotepad/runs/3117363932?check_suite_focus=true) is building cleanly.  So I have not seen this error before.  The only thing that has "Ctrl" in the value are FormMain.resx ShortcutKeys strings...  For build issues I recommend the following:
- git clean -dfx
- git checkout master
- git pull
- nuget restore ./src/XmlNotepad.sln
- msbuild ./src/XmlNotepad.sln

**Comment by TFreudi1** [comment]
That did not help. I even did a new clone. I do not have a nuget.exe so I did nuget restore from inside visual studio. The complete error output  of  the msbuild command 
[err.log](https://github.com/microsoft/XmlNotepad/files/6860711/err.log)
:

**Comment by TFreudi1** [comment]
![nuget_restore](https://user-images.githubusercontent.com/4739177/126605907-862cf4ee-c758-46f6-b76c-8fb93761bc8f.png)

**Comment by lovettchris** [comment]
Thanks the log file is what I needed, I am investigating...

**Comment by lovettchris** [comment]
I think this PR should fix it: https://github.com/microsoft/XmlNotepad/pull/114
Can you run "git pull" and try again?

**Comment by TFreudi1** [comment]
It is better one more similiar thing with "Ins"ert
XmlNotepad\src\Application\FormMain.resx(1347,5): error MSB3103: Ungültige ResX-Datei. Der angeforderte Wert "Ins" konnte nicht gefunden werden. Zeile 1347, Position 5.

**Comment by lovettchris** [comment]
Ok, I fixed that one too, try again.

**Comment by TFreudi1** [comment]
It works, Great, thanks !
