### ISSUE TITLE
Search and replace - no multiple "replace" possible

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#111]
I have
search for: Jim
replace with: John

Not possible: to click "start - replace - replace - replace ......."
(detail: Start - finds first string - replace and jumps to next string - click "replace" - "error" .....)
You have to click "Find Next" after replace ..

See screencast: https://autode.sk/3eFtJve

**Comment by lovettchris** [comment]
wow lots of great bugs, thanks.

**Comment by lovettchris** [comment]
Fixed in 2.8.0.40

**Comment by Pierre-de-la-Verre** [comment]
Fixed in 2.8.0.40
