### ISSUE TITLE
Reloading an already deleted file

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#112]
When I want to open a "recently used file .." which is already deleted, it tells me ..

"File xy.xml is not found"   -->> that's OK
"Do you want to open it with your editor?"    -->> What's the idea to open a non existing file?

(And sometimes it tells me "Missing root element" and crashes ..)

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/commit/cd1253da98fa9f036218c9ff53ae0512a858bc44 and will be available in the next published release.

**Comment by lovettchris** [comment]
Fixed in 2.8.0.40

**Comment by Pierre-de-la-Verre** [comment]
Fixed in 2.8.0.40
