### ISSUE TITLE
Refreshing an externaly modified file

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#113]
- I open the file "test.xml", the filename is both displayed in title of the software and in the "recent used files list"
- Then I open, modify and save test.xml with an editor. The save-command of the editor creates an updated "test.xml" and a backup "test.xml.bak"
- XMLNotepad changes dynamically the currently opened file to the bak, but gives no special information and shows the original file name in the list
![grafik](https://user-images.githubusercontent.com/13277944/126472174-b31513ed-5d89-458e-a52e-cd840b325c0c.png)

I'm not sure if this behaviour 
- is great or not and 
- if it should be optional and 
- if there should be a stronger advice like "hey. something changed the file. I show the backup now .."

**Comment by lovettchris** [comment]
wow this is really weird, I wonder if your other editor is "renaming" the file test.xml to test.xml.bak and somehow the file change tracking I'm using is tracking that rename...

**Comment by Pierre-de-la-Verre** [comment]
I use Ultra Edit ..
________________________________

**Comment by lovettchris** [comment]
Ok, I was tracking file renames, and clearly that's not the right thing to do in this case.  So I changed how renames are handled ion this commit: https://github.com/microsoft/XmlNotepad/commit/a4096c2be1f2186e4c8380a3d4643fbc85f07a69.  This fix will be included in the next update.

**Comment by lovettchris** [comment]
Fixed in 2.8.0.40

**Comment by Pierre-de-la-Verre** [comment]
Fixed in 2.8.0.40. No more automatic reload
