### ISSUE TITLE
xslt output shown as raw xml

### ISSUE THREAD

**Issue by rjrizzuto** [microsoft/XmlNotepad#121]
In the original 2007 XMLNotepad, transformed xml output that was html was displayed as a formatted web page.  The latest does not do that.  I am not sure if it is the tool, or if I need to change the xslt file to specify html somehow.

**Comment by lovettchris** [comment]
Hi Ray, there was a bug, which was recently fixed, can you make sure you are on [version 2.8.0.42](https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.42) ?  If you are then can you provide the xml/xslt so I can debug it?  

In the meantime workaround is to enter an explicit file name like "output.htm" in the output file text box then click the Transform button.

**Comment by rjrizzuto** [comment]
Thanks, I found that workaround also.  I am using version 2.8.0.42.  I do
not think I can provide the xml file, since it has proprietary data, but
I'll see about sending the xslt file along shortly.

**Comment by rjrizzuto** [comment]
Here’s the style sheet:

<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/TR/xhtml1/strict">
  <xsl:template match="/">
    <html>
      <body>
            <h2>Order Messages</h2>
            <table border="1">
              <tr bgcolor="#9acd32">
                <th>Message Type</th>
                <th>RequestType</th>
                <th>Order source</th>
                <th>Order Id</th>
                <th>Order Revision</th>
                <th>Ticks</th>
                <th>UTC HH</th>
                <th>MM</th>
                <th>SS</th>
                <th>MS</th>
                <th>Symbol</th>
                <th>Side</th>
                <th>Venue</th>
                <th>Open qty</th>
                <th>MM flag</th>
              </tr>
              <xsl:for-each select="//simpleOrder">
                <xsl:sort select="id_value"/>
                <xsl:sort select="id_revision" data-type="number" />
                
                
                
                  <xsl:variable name="time" select="floor(../../../enrichmentTimestamp mod (24*60*60*1000))" />
                  <tr>
                        <td><xsl:value-of select="../../../payloadType"/></td>
                        <td><xsl:value-of select="request/type"/></td>
                        <td><xsl:value-of select="id_source"/></td>
                        <td><xsl:value-of select="id_value"/></td>
                        <td><xsl:value-of select="id_revision"/></td>
                        <td><xsl:value-of select='../../../enrichmentTimestamp'/></td>
                        <td><xsl:value-of select='format-number(floor($time div (1000*60*60)),"00")'/></td>
                        <td><xsl:value-of select='format-number(floor($time div (1000*60)) mod 60, "00")'/></td>
                        <td><xsl:value-of select='format-number(floor($time div (1000)) mod 60, "00")'/></td>
                        <td><xsl:value-of select='format-number($time mod 1000, "000")'/></td>
                        <td><xsl:value-of select="instrument_symbol/value"/></td>
                        <td><xsl:value-of select="orderInstructions[1]/side"/></td>
                        <td><xsl:value-of select="executionVenue_abbreviation"/></td>
                        <td><xsl:value-of select="leavesQuantity_mantissa"/></td>
                        <td><xsl:value-of select="originatorActingAsMM"/></td>
                  </tr>
                
              </xsl:for-each>
            </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>

**Comment by rjrizzuto** [comment]
Looks like my bad, needed to add   <xsl:output method="html" encoding="utf-8" />



From: Rizzuto, Raymond
Sent: Friday, August 06, 2021 1:55 PM
To: 'Ray Rizzuto Jr' ***@***.***>; microsoft/XmlNotepad ***@***.***>
Subject: RE: [microsoft/XmlNotepad] xslt output shown as raw xml (#121)
Importance: High

Here’s the style sheet:

<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/TR/xhtml1/strict">
  <xsl:template match="/">
    <html>
      <body>
            <h2>Order Messages</h2>
            <table border="1">
              <tr bgcolor="#9acd32">
                <th>Message Type</th>
                <th>RequestType</th>
                <th>Order source</th>
                <th>Order Id</th>
                <th>Order Revision</th>
                <th>Ticks</th>
                <th>UTC HH</th>
                <th>MM</th>
                <th>SS</th>
                <th>MS</th>
                <th>Symbol</th>
                <th>Side</th>
                <th>Venue</th>
                <th>Open qty</th>
                <th>MM flag</th>
              </tr>
              <xsl:for-each select="//simpleOrder">
                <xsl:sort select="id_value"/>
                <xsl:sort select="id_revision" data-type="number" />
                
                
                
                  <xsl:variable name="time" select="floor(../../../enrichmentTimestamp mod (24*60*60*1000))" />
                  <tr>
                        <td><xsl:value-of select="../../../payloadType"/></td>
                        <td><xsl:value-of select="request/type"/></td>
                        <td><xsl:value-of select="id_source"/></td>
                        <td><xsl:value-of select="id_value"/></td>
                        <td><xsl:value-of select="id_revision"/></td>
                        <td><xsl:value-of select='../../../enrichmentTimestamp'/></td>
                        <td><xsl:value-of select='format-number(floor($time div (1000*60*60)),"00")'/></td>
                        <td><xsl:value-of select='format-number(floor($time div (1000*60)) mod 60, "00")'/></td>
                        <td><xsl:value-of select='format-number(floor($time div (1000)) mod 60, "00")'/></td>
                        <td><xsl:value-of select='format-number($time mod 1000, "000")'/></td>
                        <td><xsl:value-of select="instrument_symbol/value"/></td>
                        <td><xsl:value-of select="orderInstructions[1]/side"/></td>
                        <td><xsl:value-of select="executionVenue_abbreviation"/></td>
                        <td><xsl:value-of select="leavesQuantity_mantissa"/></td>
                        <td><xsl:value-of select="originatorActingAsMM"/></td>
                  </tr>
                
              </xsl:for-each>
            </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>

**Comment by lovettchris** [comment]
I did make [one fix ](https://github.com/microsoft/XmlNotepad/commit/32b0ccc8a9a457e67c0be2458512c996e5d2b5ff) in response to this bug report where XML notepad can be more forgiving about your actual xhtml namespace.  I notice your namespace includes the digit "1" after "xhtml" which is interesting, "http://www.w3.org/TR/xhtml1/strict" which I haven't seen before, so I changed XML Notepad so it matches any namespace containing the substring "xhtml".
