### ISSUE TITLE
Option for no-install Portable Mode

### ISSUE THREAD

**Issue by JamesO2x** [microsoft/XmlNotepad#123]
Hey, I love this app so far!

I was wondering if its possible to allow for a "Portable" version of XML Notepad? I prefer using portable apps when possible, because I like to to be able to deploy the tools I use on any machine quickly. And also the added benefit of not having to hunt down where a program is saving all of my settings is a plus: Portable software usually just saves settings to a config file directly next to the EXE (or in a "data" folder next to the EXE).

If this were possible, I could put XML Notepad in my "TOOLS" folder on my external drive, and not have to re-install it when ever I move to a different machine.

**Comment by lovettchris** [comment]
Indeed, you can already install the [standalone version](https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/XmlNotepadSetup.zip) anywhere you want and if it finds an XmlNotepad.settings file in the same folder as XmlNotepad.exe then it will use that version.  You can copy it from 
 "%USERPROFILE%\appdata\local\Microsoft\xml notepad\XmlNotepad.settings"

**Comment by JamesO2x** [comment]
@lovettchris Thanks! I just copied the program and settings over to my portable folder, and it works!

I would suggest to **add a checkbox option to the installer** labeled `Install in Portable Mode` which would just automatically place a `XmlNotepad.settings` file in the location you choose to install.

Being able to switch from Installed and Portable mode by simply moving the settings files is a very clever and awesome feature -- but it wasn't really obvious that I could do that.

Most software I run have explicitly separate builds for "installer version" and "portable version", so I wouldn't think to have done something like this if I hadn't asked.

---

Anyway, awesome work on the program, thanks!

**Comment by lovettchris** [comment]
Yes, good point thanks.  The local XmlNotepad.settings feature was added due to a previous similar customer request, but yeah, making it easier for folks to install in "portable mode" would be a nice addition.  I'll leave this issue open then until I get around to that :-)

**Comment by lovettchris** [comment]
In version 2.8.0.55 I added a new option to the Options Dialog that you might like, see [Settings Location](https://microsoft.github.io/XmlNotepad/#help/settings/).

**Comment by JamesO2x** [comment]
Cool update! I just checked it out. But since I had already manually copied my `%USERPROFILE%\appdata\local\Microsoft\xml notepad\XmlNotepad.settings` to my portable drive location, the option for "PORTABLE" was already selected. Neat!

If I had installed the program normally, then checked that option, would it automatically have moved the `%USERPROFILE%\appdata\local\Microsoft\xml notepad\XmlNotepad.settings` file to `XmlNotepad.exe` directory?

Just curious in case I need to do a clean install in the future.

**Comment by lovettchris** [comment]
yes it will move it for you.

**Comment by JamesO2x** [comment]
Awesome! Then I guess this pretty much solves the Portable Mode option. Thanks!
Issue closed!

**Comment by lovettchris** [comment]
Great, thanks for closing the issue.
