### ISSUE TITLE
I can't get the Webview2 renderer to work.

### ISSUE THREAD

**Issue by JamesO2x** [microsoft/XmlNotepad#124]
I installed Webview2, as it said on the XML Notepad site, but I can't figure out how to get XML Notepad to recognize it. It still seems to be using the old HTML renderer, and I don't see any options to change it.

**Comment by lovettchris** [comment]
[tlist.zip](https://github.com/microsoft/XmlNotepad/files/7078468/tlist.zip)

If you run XmlNotepad then run "tlist xmlnotepad" from a "cmd" prompt window, you should see all the dll's XmlNotepad has loaded, and in that list you should see these:
```
C:\Program Files\WindowsApps\5632ff08-aa93-439a-b09f-677eb3664250_2.8.0.42_neutral__b2j8apzf1bbh6\Application\runtimes\win-x64\native\WebView2Loader.dll
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\92.0.902.84\EBWebView\x64\EmbeddedBrowserWebView.dll
```

But good idea I will make it more visible which one it is using and make it also user switchable.

**Comment by JamesO2x** [comment]
I punched in `tlist xmlnotepad` and got the error response: `'tlist' is not recognized as an internal or external command,
operable program or batch file.`. This Document: "[TList - Windows drivers | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/tlist)" says that `tlist.exe` was renamed as `tasklist.exe`:

> In Windows XP and later versions of Windows, TList was replaced by TaskList (Tasklist.exe), which is described in Help and Support for those systems. TList is included in Debugging Tools for Windows to support users who do not have access to TaskList.

So I tried `tasklist xmlnotepad` and got this error response: 

```
C:\>tasklist xmlnotepad
ERROR: Invalid argument/option - 'xmlnotepad'.
Type "TASKLIST /?" for usage.
```

To verify that the `xmlnotepad` command was working, I added it to my PATHS environment variable, and ran just `xmlnotepad` and it definitely did start XML Notepad as expected.

My next step was to try `tasklist /?` to see the help documentation on how to use TASKLIST. It says I can list running services with `tasklist /svc` command. I do this, and I get a list of all my running services, but these ones are of note:

```
XmlNotepad.exe                8916 N/A
msedgewebview2.exe            1204 N/A
msedgewebview2.exe           12268 N/A
msedgewebview2.exe            8320 N/A
msedgewebview2.exe            6864 N/A
msedgewebview2.exe            6720 N/A
msedgewebview2.exe            2448 N/A
```

So XmlNotepad and Webview2 are definitely running. But this command lists only EXEs as a flat list, and doesn't show which DLLs are loaded by which program. The help says I can check which modules are loaded with `tasklist /m`, which gives me a HUGE list. I use `CTRL + F` to search for `xmlnotepad.exe` and find this info:

```
XmlNotepad.exe                8916 ntdll.dll, MSCOREE.DLL, KERNEL32.dll,
                                   KERNELBASE.dll, ADVAPI32.dll, msvcrt.dll,
                                   sechost.dll, RPCRT4.dll, mscoreei.dll,
                                   SHLWAPI.dll, kernel.appcore.dll,
                                   VERSION.dll, clr.dll, USER32.dll,
                                   win32u.dll, VCRUNTIME140_CLR0400.dll,
                                   ucrtbase_clr0400.dll, GDI32.dll,
                                   gdi32full.dll, msvcp_win.dll, ucrtbase.dll,
                                   IMM32.DLL, psapi.dll, mscorlib.ni.dll,
                                   ole32.dll, combase.dll,
                                   bcryptPrimitives.dll, uxtheme.dll,
                                   CRYPTSP.dll, rsaenh.dll, bcrypt.dll,
                                   CRYPTBASE.dll, clrjit.dll, System.ni.dll,
                                   System.Drawing.ni.dll,
                                   System.Windows.Forms.ni.dll,
                                   System.Core.ni.dll,
                                   System.Configuration.ni.dll,
                                   netstandard.ni.dll, System.Xml.ni.dll,
                                   shell32.dll, windows.storage.dll, Wldp.dll,
                                   SHCORE.dll, profapi.dll, MSCTF.dll,
                                   OLEAUT32.dll, comctl32.dll, rasapi32.dll,
                                   rasman.dll, rtutils.dll, WS2_32.dll,
                                   mswsock.dll, winhttp.dll, IPHLPAPI.DLL,
                                   NSI.dll, dhcpcsvc6.DLL, dhcpcsvc.DLL,
                                   gdiplus.dll, DWrite.dll, TextShaping.dll,
                                   comctl32.dll, clbcatq.dll,
                                   dataexchange.dll, d3d11.dll, dcomp.dll,
                                   dxgi.dll, twinapi.appcore.dll,
                                   WindowsCodecs.dll, urlmon.dll,
                                   iertutil.dll, netutils.dll, srvcli.dll,
                                   SspiCli.dll, PROPSYS.dll,
                                   System.Data.SqlXml.ni.dll, tiptsf.dll,
                                   WebView2Loader.dll,
                                   EmbeddedBrowserWebView.dll,
                                   textinputframework.dll, CoreMessaging.dll,
                                   CoreUIComponents.dll, wintypes.dll,
                                   ntmarta.dll, edputil.dll, apphelp.dll,
                                   DNSAPI.dll, WINNSI.DLL, mdnsNSP.dll,
                                   rasadhlp.dll, fwpuclnt.dll, secur32.dll,
                                   schannel.DLL, mskeyprotect.dll, NTASN1.dll,
                                   ncrypt.dll, ncryptsslp.dll, crypt32.dll,
                                   MSASN1.dll
```

In the list of DLLs, you can see that `WebView2Loader.dll` and `EmbeddedBrowserWebView.dll` are indeed loaded under `xmlnotepad.exe`.

---

I decided to close everything, start XML Notepad again, and load one of my XML files that I was having issues with before. It **does appear** that the Webview2 is now working as intended. Before when I first reported this issue, modern CSS and other features you'd expect were not working (which is how I was able to tell the Webview2 wasn't being used, and that it was loading the old renderer).

But it seems to be working now. When I first had this issue my instinct was to restart the computer so that Webview2 would fully install and load, but that didn't work initially. But since then, I have shutdown my computer several times since I first installed Webview2 and reported this issue. Maybe it just needed a full Shutdown? Not sure.

_**Anyway, the issue seems to have resolved itself after several shutdown/bootups. You can mark this as solved.**_

---

NOTE: I'm including all the steps I took above for reference in case anyone wants to reproduce them or has a similar issue getting Webview2 to load. For reference, 

I'm running on the latest version of Windows 10 as of (2021-08-31). The process may vary if you're using a different version of Windows.

**Comment by lovettchris** [comment]
Thanks for finding tasklist and using it like that, very cool.  I'm glad to hear it is now working.  I'm going to add more diagnostics to the code to report if/why webview2 is not loading.  Interesting to hear it may need some full reboots, even a shutdown/restart.  I don't recall running into these issues when I was implementing the feature, but I will add some helpful text to prompt folks to try a full reboot if they expect webview2 to be working but find it is not.  Thanks for reporting this.

**Comment by lovettchris** [comment]
Ok, I published a new version 2.8.0.43 which adds 2 new [XSLT options to the options dialog](https://microsoft.github.io/XmlNotepad/#help/options/#xslt).  You can now toggle between the old WinForms webbrowser and the new WebView2 component and when you do it will tell you if and why the WebView2 fails to initialize.

**Comment by JamesO2x** [comment]
@lovettchris Thanks! I just downloaded the new version., I'm gonna try it out.

So, I just tested it. When I first opened the new version 2.8.0.43 it seemed to revert back to using the old HTML renderer. I closed XML Notepad, and reopened it, and still it was stuck on the old renderer. I checked the options panel, and "Webview2" was definitely selected in the settings.

So what I did was I switched that option to "Winforms Web Browser", then clicked OK to confirm. Next, I opened the Options panel again, and changed that setting back to "Webview2", pressed OK to confirm. Once I did that, the Webview2 renderer kicked in instantly and the Output tab was updated.

I closed the program and re-opened it a couple times to check if the Webview2 setting would stick -- Yes, now Webview2 is properly loading every time I start XML Notepad.

So yeah, it seems something goofy is happening when XML Notepad tries to load Webview2. But it seems like once it does "get it" the setting sticks and works every time after that.

I wonder if it might just be a quirk of Webview2?

**Comment by lovettchris** [comment]
hmmm, super interesting, thanks for the report, I will do some more digging on the initial setup, it sounds pretty wonky that you had to do a couple switches back and forth like that, but I'm glad you are in a final state that is working.

**Comment by lovettchris** [comment]
closing for now.
