### ISSUE TITLE
Fails to open files with spaces in the file name

### ISSUE THREAD

**Issue by kevinee** [Microsoft/XmlNotepad#13]
Firstly: very useful app, thank you!

eg. filename = "My File.xml"
Right click on the file, select "open with..", select xmlnotepad
Fails with errors, cannot find "My" and cannot find "File.xml"
Presumably this would also happen if double clicking that xml file and xmlnotepad was the default app for xml extension.
Workaround: Use the file>open menu option in xmlnotepad

**Comment by shadolight** [comment]
Not sure how it happened, but this is actually a Windows Shell issue, and not a XmlNotepad issue. But it is quite easy to fix.

To fix, open regedit.exe and do Edit|Find menu option. Specify "xmlnotepad.exe" as the 'Find what' term. Make sure that for every result where the result is either a '..->Shell->Edit->Command' key or '..->Shell->Open->Command' that the %1 command line argument is inside inverted commas i.e. "%1".

For example, if the value is like this:
"C:\Program Files (x86)\LovettSoftware\XmlNotepad\XmlNotepad.exe" %1
then use 'Modify' to edit the string to this:
"C:\Program Files (x86)\LovettSoftware\XmlNotepad\XmlNotepad.exe" "%1" 

As always, make a backup (or restore point) of your registry before manual editing.

**Comment by lovettchris** [comment]
I tested this works fine on Windows 10, so must have been an old windows bug.
