### ISSUE TITLE
Issues parsing Ampersand & in a file?

### ISSUE THREAD

**Issue by UlrichPrinz** [microsoft/XmlNotepad#131]
Sorry, if this this my mistake, I am not an expert in XML - new to the game.
I have a XML File with Elements that sometimes have "&" ampersands in them.
Example below -> It will give back the Error Message: 
**"Error loading: <filename>
  An error occured while passing EntityName. Line 7, position 25."**

Ampersands are normal part of Data, often used in Company names.
I am surprised (and suspicious)  that I should be the first to notice this - maybe I am doing something wrong?

I have added a simple file to demonstrate it, there is an ampersand in line 7:

```
<result>
<sys_updated_on>
<display_value>2020-12-10 14:50:16</display_value>
<value>2020-12-10 13:50:16</value>
</sys_updated_on>
<CompName>
<display_value>Hewlett & Packard</display_value>
<value>BSN0001732</value>
</CompName>
</result>

```

**Comment by lovettchris** [comment]
Hi, yes this is illegal XML format.  The [W3C XML specification](https://www.w3.org/TR/REC-xml/#syntax) took a hard stance on the use of ampersand.  You see in XML (and in HTML) the empersand is a special character preceding the name of a special "ENTITY".  For example, in HTML the following "&pound;" is rendered as "£".  HTML is "relaxed" and lets you still write & by itself.  XML is not.  XML is designed to be 100% unambiguous as a machine readable format this means in XML "&" must be followed by a legal entity name and a semicolon.  So how do you get an actual ampersand into your XML content?  You have to use the special entity for ampersand which is "&amp;".  So the above needs to be:
```xml
<display_value>Hewlett &amp; Packard</display_value>
```
Whatever tool generate the above XML needs to be rewritten to produce well formed XML.  This can be done easily if you use the [XmlWriter](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlwriter?view=net-5.0) class from Microsoft.

**Comment by UlrichPrinz** [comment]
Hey Chris,
Wow! Thanks for taking the time to explain this in such detail!
I guess I should have Googled it myself, sorry.
Great Service - You are a star! :-)
U.Prinz
