### ISSUE TITLE
"Edit mode" covers the next line

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#149]
When I "select" a line, there is no problem to read the next line:
![grafik](https://user-images.githubusercontent.com/13277944/140963667-f6ea3a93-97f5-4557-bb7f-b766f806c7d9.png)

But when I edit the line, it covers the half of the following line:
![grafik](https://user-images.githubusercontent.com/13277944/140963819-0515ddcc-2b01-4575-8ded-e97640c6175b.png)
So it is not easy to read and to select the next line.

Maybe this can be improved?

**Comment by lovettchris** [comment]
Yeah I see that, the thing is this is a multi-line text editor and in the multiline case it is an "overlay" that sits on top of the underlying panel like this:
![image](https://user-images.githubusercontent.com/18707114/141000541-265486ac-7002-4969-a2d8-b22ee312eee3.png)

but yeah, I can try and make the single line editor smaller...

**Comment by lovettchris** [comment]
Fixed here https://github.com/microsoft/XmlNotepad/pull/156

**Comment by lovettchris** [comment]
You can now try it here: https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.48

**Comment by Pierre-de-la-Verre** [comment]
Thanks
![grafik](https://user-images.githubusercontent.com/13277944/143424403-ed9834d0-f357-40b6-9a2b-5941a7c3648f.png)
