### ISSUE TITLE
Opensource version?

### ISSUE THREAD

**Issue by ArsenShnurkov** [Microsoft/XmlNotepad#15]
Quick analysis give dependency from COM mshtml. Is it possible to build this application without it ?

<pre> <a href="https://github.com/Microsoft/XmlNotepad/blob/3b535aab410e9b08c0ce3a81b4be5f8b1e78e71d/src/XmlNotepad/XmlNotepad.csproj#L295">Microsoft.mshtml</a>, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL
 PresentationCore
 PresentationFramework
 UIAutomationClient
 UIAutomationTypes
[~] Accessibility
[~] Microsoft.CSharp
[~] System
[~] System.Core
[~] System.Data
[~] System.Data.DataSetExtensions
[~] System.Deployment
[~] System.Drawing
[~] System.Windows.Forms
[~] System.Xaml
[~] System.Xml
[~] System.XML
[~] System.Xml.Linq
[~] WindowsBase</pre>

**Comment by lovettchris** [comment]
The XsltViewer uses mshtml to render HTML.  So you would have to comment out that feature or find another browser to use instead of that.
