### ISSUE TITLE
Button to select XSLT-Output

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#152]
(I thought I wrote this already yesterday, but can not find it any more ..)

The Button to select XSLT-Output opens an "Open file - dialogue" and not a "Save as - dialogue". It is intended?

**Comment by lovettchris** [comment]
Good bug, and thanks for all the new bugs, long time no chat :-)

**Comment by lovettchris** [comment]
Fixed here https://github.com/microsoft/XmlNotepad/pull/156

**Comment by lovettchris** [comment]
You can now try it here: https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.48

**Comment by Pierre-de-la-Verre** [comment]
Thanks.
