### ISSUE TITLE
Mouse display in XSL-Output

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#153]
Moving around the mouse in "XSL-Output" it shows me on different places the
- standard cursor (Arrow)
- "edit cursor"(?)
- "press the link - finger cursor"

What is the last one good for? Could it be avoided?

**Comment by lovettchris** [comment]
it is a web browser component, so it does whatever a web browser would do with your CSS styles, and this is outside the control of XML notepad.  For example, I can follow the links in the rsspretty output and get to all sorts of fun places:

![image](https://user-images.githubusercontent.com/18707114/143303290-86b67c6d-a536-43bf-8bab-ceae9c9d8137.png)

**Comment by Pierre-de-la-Verre** [comment]
I found the "click-the-link finger" also on

`<Basket xsi:noNamespaceSchemaLocation="basket.xsd" language ..`

and this is why I asked. It's good for me.

**Comment by lovettchris** [comment]
oh, that might be trying to do expand collapse, but it doesn't seem to be working :-)
