### ISSUE TITLE
Wish: Add "last used files" to XSLT-Location

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#154]
I hope the image declares it enough:
![grafik](https://user-images.githubusercontent.com/13277944/143263200-c8af7977-b088-4bd9-af84-6df4dd704be9.png)

**Comment by lovettchris** [comment]
I see some possibilities here, which is your preference?

1. a single global list of every xslt file ever entered on any xml file, remembered across xml notepad sessions
2. a global list, but not remembered across xml notepad sessions
3. a context sensitive list (separate list for every XML file you edit) not remembered
4. a context sensitive list (separate list for every XML file you edit) remembered across sessions...

**Comment by Pierre-de-la-Verre** [comment]
I will see tomorrow. Hope that other user will reply too.
________________________________

**Comment by lovettchris** [comment]
I added a quick and dirty global list here if you want to try building it locally to try it out:
#156

**Comment by lovettchris** [comment]
You can now try it here: https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.48

**Comment by Pierre-de-la-Verre** [comment]
OK for me for first test.
