### ISSUE TITLE
Wish: to not transform imediately on XSL Output

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#157]
When calling the "XSL Output - Tab", it starts immediately to transform.  Good for files with defined XSLT or small XML.

For me, I use XML > 5 MB with external XSLT, and a "standard-transform" often only wastes time - I have to select the external XSLT and transform again.

A new option would help like "For files which contains no xml-stylesheet processing instruction - do you want a standard-transformation?
- always?
- only up to filesize of ?? MB
- never?

(a limit with 0 MB would replace the never" option, a file with 9999 MB the "always" option)

**Comment by lovettchris** [comment]
How about I add an Option in the options dialog to "disable" the "XML formatting default stylesheet" so you see only this:

![image](https://user-images.githubusercontent.com/18707114/143510850-1c4c17b4-2b0e-4e78-b947-019e36f547a9.png)

This way it will always be super quick and not waste your time...

**Comment by lovettchris** [comment]
Try this version: https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.49

**Comment by Pierre-de-la-Verre** [comment]
Thanks. Good for me.
