### ISSUE TITLE
F1 - Help: Not up to date?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#158]
it seems that here
`file:///C:/Program%20Files%20(x86)/LovettSoftware/XmlNotepad/Help/help/menus.htm`
are missing some new features: Duplicate, Statistic, ..

Edit: Here too:
[http://microsoft.github.io/XmlNotepad/#help/menus/](http://microsoft.github.io/XmlNotepad/#help/menus/)

**Comment by lovettchris** [comment]
Fixed
