### ISSUE TITLE
xmlstats: which version?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#159]
The command "View - Statistics" shows me "2.8.0.48"; c:\Program Files (x86)\LovettSoftware\XmlNotepad\XmlStats.exe is from March 2021 and version 2.8.0.27.

What should be installed?

**Comment by lovettchris** [comment]
Weird you should see this, can you delete the one in %TEMP%\XmlNotepad and try again?  I wonder if it is a caching issue...

![image](https://user-images.githubusercontent.com/18707114/143509669-59affc7f-4b5d-4685-b351-5a8a73cf3b8e.png)

**Comment by Pierre-de-la-Verre** [comment]
Sorry - my bad.
Some times ago I copied the EXE from %TEMP%\XmlNotepad (which is for me a strange place for a software) to the program-folder, and now I messed it up.
