### ISSUE TITLE
Menu "Window - New Window"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#160]
My software terminology is not the best, but ...
I'm not sure - is it really a "window" (IMHO a kind of sub-feature of the current software-session) or a new "software session"?

**Comment by lovettchris** [comment]
Right I think "New Window" usually means a new unrelated editing session.  For example "File/New Window" in Visual Studio Code is literally an entirely new session.  Whereas "New View" if it supported that would mean a new "view" of the same document where you would expect that "View" to remain in sync with edits that happen in either.  So I think "New Window" is ok in this case, although it could be collapsed into the File menu, not really any need to have a separate menu for it, but it used to be a kind of standard many eons ago, when the earth was still cooling, to have "File/Edit/View/Window/Help" as well as any app specific ones, see https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/
