### ISSUE TITLE
Icon of Internet Explorer beside "XSLT LOcation"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#161]
Is it a decoration or does it give some information or does it change sometimes, depending on ... ??

**Comment by lovettchris** [comment]
Yeah, I suppose I should switch to this new icon which is the SymbolFont icon for internet:
![image](https://user-images.githubusercontent.com/18707114/143657073-9e019a5e-aa6b-45ec-b385-66d72a677c0e.png)

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/v2.8.0.50
