### ISSUE TITLE
Question: Best way to merge XML-files?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#165]
I know, the standard way(?) to merge the content of XML-files is a XSLT. But nevertheless, ..

1. Does XMLNotepad have some special tricks for it?
2. Are there some command-line feature for it?
3. How to "Copy & Paste" full structure "into" the same structure and not "beside it? Example ..
I wanted to paste the entire content of the "datasection" from File A into the "datasection" of File B. The result can be seen: I have two datasections ..
![grafik](https://user-images.githubusercontent.com/13277944/143870250-c96f229b-5e5c-481b-b77c-4b88a19dec47.png)

Can it be done or is this beyond the basic idea of XML?

**Comment by lovettchris** [comment]
The XmlDiff library I'm using to do "Compare XML Files" actually can also apply that "diff" to "merge" changes from one file to another... but I have not provided any UI for doing that yet...  but I agree it would be nice to have a "merge on paste" option that does what you are suggesting.

**Comment by Pierre-de-la-Verre** [comment]
Hi Chris
something new with this topic?

**Comment by Pierre-de-la-Verre** [comment]
Closed. I think the idea is not good; it's out of the target of this software to replace XSLT.
