### ISSUE TITLE
Unicode Tabulator and CRLF are ignored in XSLT

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#166]
I have a XSLT where I use the unicode for TAB and CRLF - "`&#0009;`" and "`&#xa;`". Both are not display in XMLNotepad
![grafik](https://user-images.githubusercontent.com/13277944/143876739-e1aaadb3-02e3-4aaf-aa56-9b37382d24ac.png)
Issue on which side of the keyboard?

**Comment by lovettchris** [comment]
Yes, XML notepad is showing you the "post whitespace normalization" view of the file.  To see some of your whitespace you may need to add this attribute to the top element in your file: 
```xml
 xml:space="preserve"
```

**Comment by Pierre-de-la-Verre** [comment]
You know, I'm the "option guy" ;-) Could it also be solved with an option?

**Comment by lovettchris** [comment]
Well try the xml:space="preserve" trick and see what it does - you get a whole bunch of new nodes named "SignificantWhitespace" which you might not like either...

**Comment by Pierre-de-la-Verre** [comment]
Yes, I see. Thanks.
