### ISSUE TITLE
Open a non-exisiting file with text-editor?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#167]
I opened "file x", opened it also in an editor, changed it and renamed it. Coming back to XMLNotepad it asks me: "File has changed, do you want to reload". After "Yes" it tells me:
![grafik](https://user-images.githubusercontent.com/13277944/143878146-e9c19bca-0eb8-4d28-89ff-c36415ae836b.png)
Does this make sense? Open a non-existent file with text-editor? Maybe there is a confusion between "error-load" and "non-load"?

**Comment by lovettchris** [comment]
excellent bug, thanks for reporting it.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.51

**Comment by Pierre-de-la-Verre** [comment]
The MSI inside the "setup.zip" is from Nov. 27. Seem to be the old version ..

**Comment by lovettchris** [comment]
Woops - please try this version:
https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.52

**Comment by Pierre-de-la-Verre** [comment]
Hmm

- I open d:\Downloads\XmlNotepadSetup\Updates.xml with XMLNotepad - OK
- I open d:\Downloads\XmlNotepadSetup\Updates.xml with Ultra Edit - add a trailing space - save it
- I get: ![grafik](https://user-images.githubusercontent.com/13277944/145006810-4dc2c126-5ec9-43b8-bc59-a131fe63f644.png)
- Pressing "Yes" I get: 
![grafik](https://user-images.githubusercontent.com/13277944/145007072-496c19a4-4491-450f-a5a7-71a6f10276e8.png)

**Comment by lovettchris** [comment]
Yikes, I'll take another look... thanks for the bug report.

**Comment by Pierre-de-la-Verre** [comment]
Strange - it seem to be a special problem of Ultra Edit. It creates a BAK-file, maybe that's the reason.

Edit and save with "Notepad" - works fine: "File has changed, ..."
Renaming the file works fine too: "Has been renamed ..."

**Comment by lovettchris** [comment]
Ok, I found a fix for this, I will ignore renames to files ending in ".bak".  The fix will be in the next release.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.53

**Comment by Pierre-de-la-Verre** [comment]
Thanks.
