### ISSUE TITLE
Default name for XSLT-Output-filename

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#168]
When there is no defined name for the XSLT-Output-file, the software use "Name of XSLT plus (inside XSLT) defined extension".
That's fine when using same XML with different XSLT.
But just as well could be "Name of XML plus (inside XSLT) defined extension" - when using different XML with same XSLT.

What do you think about it?

**Comment by lovettchris** [comment]
Perhaps, but that doesn't work for the xsl:output type of "xml" :-)

**Comment by Pierre-de-la-Verre** [comment]
Why?
