### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by elvogel** [Microsoft/XmlNotepad#17]
Any chance we could get it to support opening and reading RSS feeds? Currently, it breaks on the `rss` declaration at the top. 

thanks!

**Comment by lovettchris** [comment]
XML Notepad can load this rss feed just fine, which one are you loading?

![image](https://user-images.githubusercontent.com/18707114/26892915-9fa0f8ce-4b6e-11e7-863a-8faa6a425bc4.png)

**Comment by elvogel** [comment]
my own - which (as it turns out) doesn't have the XML declaration, only the RSS declaration...

**Comment by lovettchris** [comment]
The xml declaration is optional, so I'm guessing you are hitting an encoding problem.  See [How to encode XML data](https://msdn.microsoft.com/en-us/library/aa468560.aspx).
