### ISSUE TITLE
Reload and unlaod of modified files

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#173]
Hi Chris
I hope you are fine?

It's more a luxury problem, but try this. 
- Create a XML file with this wrong header:
`<?xml version="1.0" encoding="testtest" ?>`
- Try to open it
- you will get an error message
- let XMLNotepad unchanged
- edit the XML in another editor to a correct header - save - watch - write a wrong header again - save ...

It displays a dialogue "Do you want to ..." - but it does not wait, it re/unloads for it's own.

**Comment by lovettchris** [comment]
Should be fixed by commit https://github.com/microsoft/XmlNotepad/commit/57e1668b6e14c1866db6742ad4c3df55ad440c6f

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.53

**Comment by Pierre-de-la-Verre** [comment]
Thanks

**Comment by Pierre-de-la-Verre** [comment]
Problems with file "rdcman.rdg" from "Remote Desktop Connection Manger" at https://docs.microsoft.com/de-de/sysinternals/downloads/rdcman 
- Open file with XMLNotepad
- Save it with rdcman
- XMLNotepad tells me: File has changed. Do want to reload?
- Yes
- It tells me: "The file you are to open no longer exists" - although it exists

**Comment by lovettchris** [comment]
fixed in new version 2.8.0.58.
