### ISSUE TITLE
File title versus file-history

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#175]
I'm not sure if that's great or confusing ..

- Open file a.xml in XMLnotepad
- "a.xml" is displayed in caption of program and in history-list
-  Open file b.xml in another XMLnotepad session
- "b.xml" is displayed in caption of program and in history-list of second session
-  close "session b"
- "a.xml" is still displayed in caption of "Session A" and history-list changes to "B.xml" 

I think if it's a real history, then the currently opened file should not be displayed..
![grafik](https://user-images.githubusercontent.com/13277944/155535409-bb7d47a6-3ef3-4fae-92bb-076463d1a121.png)

**Comment by lovettchris** [comment]
Should be fixed by commit https://github.com/microsoft/XmlNotepad/commit/6f040c47cfee560575f33c6d9226fe2603c54b7f

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.53

**Comment by Pierre-de-la-Verre** [comment]
Thanks number 3

**Comment by Pierre-de-la-Verre** [comment]
I have to open this again, because it is still (or again) confusing me.

To reproduce:
Double click  on A.xml - it is opened
Double click  on B.xml - it is opened
Double click  on C.xml - it is opened
I have three sessions; in each I have the current file in the caption of the software and in the "recently used files".
Problem A: The caption shows only the filename, the MRU shows full path.
![grafik](https://github.com/user-attachments/assets/236d4522-e976-4812-8603-a445c0f8c4de)

- (Optionally: Open in one of the sessions (e.g. in Session B) the file something.xml)
- Close one of the sessions (e.g. "B")
- -->> The currently used file from session B appears in the "Recently list" from active sessions A and C.
![grafik](https://github.com/user-attachments/assets/4db028e8-7137-4f05-a517-bbca223dcfcd)

I'm still not sure if this is a) more helpful or b) more confusing. (Personally, I tend to b). But in any case, it is a unique feature - I'm not aware of another software. 
(But maybe it is caused because there are not three sessions but only three windows of one session? Or so ...??)
-
