### ISSUE TITLE
New 'DisableUpdateUI' setting 

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#179]
Where can I find it?

**Comment by lovettchris** [comment]
You have to add it manually to your XmlNotepad.settings file.  I provided no "UI" for editing this option.  It's like an "administrator" option that someone would setup for all machines installing XmlNotepad in an enterprise, for example.

**Comment by lovettchris** [comment]
See also this new feature which is related:
https://github.com/microsoft/XmlNotepad/issues/180
