### ISSUE TITLE
Multi-user enteprise-wide deployment with custom xmlnotepad.settings.template

### ISSUE THREAD

**Issue by lsansan** [microsoft/XmlNotepad#180]
Maybe it could be useful having a xmlnotepad.settings template with default options in this use case.  I mean, maybe you have a computer where several users can login and you want to provide default settings. You could use a portable installation but then you only have a global xmlnotepad.settings for every user (unless you duplicate the installation for each user).

The idea would be:
- Add a xmlnotepad.settings.template. It would be a standard xmlnotepad.settings.
- If there is a xmlnotepad.settings in the installation folder, the app would use it.
- If there is not a a xmlnotepad.settings in the installation folder, the app would load the xmlnotepad.settings.template and save it to appdata local or roaming depending on the configuration.

**Comment by lovettchris** [comment]
Interesting idea, but Windows has lots of specialized ways to do centrally managed software distribution for enterprise, so I'd rather not re-invent this wheel just for XML notepad.  Besides I'm not sure anyone would use the xmlnotepad.settings.template feature...

**Comment by lsansan** [comment]
Thank you for considering it.  It is very common having a default configuration file (template) with the system installation and, when you launch the application for the first time, the config file is copied to the users local or roaming profile (Notepad++ works in this mode). Some applications have the global configuration in the system in programdata folder. 

For enterprise distribution is not so easy (I'm not an expert) if you want a system installation because you don't know what user will login in a computer. This is only if you want a default config and also allow each user to change it. Maybe you can configure the default user profile but it is weird.

Thank you again. I understand you have to prioritize and this is not a common feature for individuals.

**Comment by lovettchris** [comment]
Ok, you convinced me.  It's super easy to do anyway, so it's now on my list... :-)

**Comment by lovettchris** [comment]
Here's the code for it in case you want to take it for a test drive:
https://github.com/microsoft/XmlNotepad/commit/ea6f084bd49590545ed7cba05c8d912e0d6016ba

**Comment by lsansan** [comment]
Thank you. It works great.

Maybe in future releases you could consider to handle Allow Analytics or DPI configuration in the default config template directly instead of the Env variables XML_NOTEPAD_DISABLE_ANALYTICS or XML_NOTEPAD_DISABLE_HIGH_DPI. 

For me it is ok 👍 👍

**Comment by lovettchris** [comment]
You can in fact disable analytics in the XmlNotepad.template.settings, see https://microsoft.github.io/XmlNotepad/#help/analytics/ which says these settings will do it:

```xml
<Settings>
  <AnalyticsClientId>disabled</AnalyticsClientId>
  <AllowAnalytics>False</AllowAnalytics>
</Settings>
```

**Comment by lsansan** [comment]
Perfect. I can also configure that in the template :)

Thank you!
