### ISSUE TITLE
Error when changing from roaming to local (1st time use)

### ISSUE THREAD

**Issue by lsansan** [microsoft/XmlNotepad#182]
The first time you open XML Notepad, if you change settings location from Roaming To Local, you get an error ("settings were not moved"). That is because the configuration file does not exist yet in the Roaming Profile, and it is trying to copy it from it.

I'm not sure what is the best way to handle it. A quick fix could be save the default configuration in the roaming profile when the app is first launched.  Maybe a further analysis is required.

**Comment by lovettchris** [comment]
Ha ha, great bug, thanks.

**Comment by lovettchris** [comment]
Fix checked in, see [commit ](https://github.com/microsoft/XmlNotepad/commit/53d694132d034d71dcbc0e581a2c3f05e258619d. 
 It will be included in the next release.
