### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Bavarello** [microsoft/XmlNotepad#184]
Edizione	Windows 10 Pro
Versione	21H2
Data installazione:	‎18/‎06/‎2020
Build sistema operativo	19044.1620
Esperienza	Windows Feature Experience Pack 120.2212.4170.0

public 2.8.0.56  At every start there is this notice. 

System.IO.FileNotFoundException: The file or assembly 'Newtonsoft.Json, Version = 13.0.0.0, Culture = neutral, PublicKeyToken = 30ad4fe6b2a6aeed' or one of its dependencies could not be loaded. Cannot find the specified file.
Filename: 'Newtonsoft.Json, Version = 13.0.0.0, Culture = neutral, PublicKeyToken = 30ad4fe6b2a6aeed'
   in GoogleAnalytics.HttpProtocol. <PostMeasurements> d__0.MoveNext ()
   in System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start [TStateMachine] (TStateMachine & stateMachine)
   in GoogleAnalytics.HttpProtocol.PostMeasurements (Analytics a)
   in XmlNotepad.AppAnalytics. <SendMeasurement> d__11.MoveNext ()
--- End stack trace from previous location where exception was thrown ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()

AVV: Assembly binding registration is disabled.
To enable assembly binding error logging, set the [HKLM \ Software \ Microsoft \ Fusion! EnableLog] (DWORD) registry value to 1.
Note: Some performance penalties are associated with logging assembly binding errors.
To disable the feature, remove the [HKLM \ Software \ Microsoft \ Fusion! EnableLog] registry value.

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4470.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XmlNotepad
    Versione assembly: 2.8.0.56
    Versione Win32: 2.8.0.56
    Base di codice: file:///D:/Programmi/XmlNotepad/XmlNotepad.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4488.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4488.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4470.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
XmlNotepad.Model
    Versione assembly: 2.8.0.56
    Versione Win32: 2.8.0.56
    Base di codice: file:///D:/Programmi/XmlNotepad/XmlNotepad.Model.DLL
----------------------------------------
netstandard
    Versione assembly: 2.0.0.0
    Versione Win32: 4.8.4084.0
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Microsoft.XmlNotepad
    Versione assembly: 2.8.0.56
    Versione Win32: 2.8.0.56
    Base di codice: file:///D:/Programmi/XmlNotepad/Microsoft.XmlNotepad.DLL
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Versione assembly: 1.0.1150.38
    Versione Win32: 1.0.1150.38
    Base di codice: file:///D:/Programmi/XmlNotepad/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Versione assembly: 1.0.1150.38
    Versione Win32: 1.0.1150.38
    Base di codice: file:///D:/Programmi/XmlNotepad/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Data.SqlXml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
SimpleGoogleAnalytics
    Versione assembly: 1.1.0.0
    Versione Win32: 1.1.0.0
    Base di codice: file:///D:/Programmi/XmlNotepad/SimpleGoogleAnalytics.DLL
----------------------------------------
System.Net.Http
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Xml.Xsl.CompiledQuery.1
    Versione assembly: 0.0.0.0
    Versione Win32: 4.8.4084.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by lovettchris** [comment]
Great, If all is good for you then go ahead and close the issue, thanks.
