### ISSUE TITLE
"Options" dialogue does not remember its position

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#186]
The option dialogue should store its size, position and the width of the columns. Now it is slowly "wandering across the screen" with each call ..

**Comment by Bavarello** [comment]
I have more or less the same problem. This is what you see.

![Immagine 2022-04-02 223422](https://user-images.githubusercontent.com/22433856/161400415-ad4c7285-1d7f-407d-9660-572e344b9efc.jpg)

**Comment by lovettchris** [comment]
Will be fixed in 2.9.0.6
