### ISSUE TITLE
XMLStats: some questions for params

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#194]
-val: (fictional)
Is it possible / can it be added to show only defined values? Like "xmlstats -val "owner, area" -f myfile.xml

-f:
I get a (summary) result, but don't know what it contains. Please add in header the files which are used

-f -v:
I defined three files - a.xml, b.xml, c.xml.
The result file shows me:
- title A
- data A
- title B
- data B
- title C
- summary data

Is this intended?
Thanks!

**Comment by Pierre-de-la-Verre** [comment]
Bump up ...

**Comment by lovettchris** [comment]
So to be clear the `-f` option should point to a file containing a list of file names and not `myfile.xml`.  

For example:
```
cd D:\git\lovettchris\XmlNotepad\src\Application\Samples
dir /b *.xml > list.txt
xmlstats -f list.txt
```
This will report a combined report of everything found in all the XML files listed in `list.txt`.

**Comment by lovettchris** [comment]
Now for your `-val` option it sounds like you want a kind of "selector" that is saying only report the status on matching nodes. So along those lines, what do you think of making this "selector" an XPath expression?  Something like this:

```
xmlstats Hamlet.xml -select "//SPEECH"
```
would output only the stats for those matching elements in the hamlet.xml file.  Then I would allow multiple `-select` arguments so you can specify different xpath expressions if needed.

Would this be useful?

**Comment by Pierre-de-la-Verre** [comment]
> would output only the stats for those matching elements in the hamlet.xml file. Then I would allow multiple `-select` arguments so you can specify different xpath expressions if needed.

Yes, I think this would to the job. Thanks.

**Comment by Pierre-de-la-Verre** [comment]
> This will report a combined report of everything found in all the XML files listed in `list.txt`.

Yes, I did it in two versions:

```
xmlstats  -f list.txt > -f.txt
xmlstats -v -f list.txt > -v-f.txt
```
The results are attached
[-f.txt](https://github.com/microsoft/XmlNotepad/files/9533780/-f.txt)
[-v-f.txt](https://github.com/microsoft/XmlNotepad/files/9533781/-v-f.txt)

f.txt contains:
- no info about the files which are analysed
- a lot a statistics

v-f.txt contains:
- path for basket.xml
- data for basket.xml
- path for employee.xml
- data for employee.xml
- path for hamlet.xml
- data for hamlet.xml
- path  for rss.xml
- data for ????. It seems that data.rss.xml is missing and is followed by the same (summarized) data package which is in -f.txt

**Comment by lovettchris** [comment]
Ah, ok, I see what you mean, I added the file names in the -f case with this fix: https://github.com/microsoft/XmlNotepad/commit/a003cae254b86acb0f32a658ca1215b15f06aec1

**Comment by lovettchris** [comment]
XPath turned out to be too complex, so I went for a simpler option, similar to what you proposed, the new argument is "-s" for "select" and you can select element names (using local names, so you don't have to worry about namespace prefixes).  You can try it out here: https://github.com/microsoft/XmlNotepad/commit/7a767e2b8fee7f056d63651cd9612b6c0c56ca50

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.63
