### ISSUE TITLE
Please publish code for Notepad as well

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/XmlNotepad#195]
It's more of a vain wish rather than a feature request, so feel free to close this issue! :)

On the serious note, it would be very welcome and modern Notepad would iterate much faster. Would appreciate if you could pass this wish to the Notepad / Windows team.

**Comment by clovett** [comment]
[This is a version](https://github.com/SystemNotepad/Notepad), not the actual windows app, but it's a start.
