### ISSUE TITLE
XSLT-Output: new file removes old one

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#199]
I create an XSLT-transform, ..

- define "a.txt", transform
- a.txt is created
- define "b.txt", transform
- b.txt is created, a.txt is removed
- define "xx.html", transform
- xx.html is created, b.txt is removed

https://user-images.githubusercontent.com/13277944/166421998-2bd1fb5e-5afb-4d5d-a23f-1cef6ba89569.mp4

Seem to be a bug for me - see attached screencast

**Comment by Pierre-de-la-Verre** [comment]
I found it while testing a myfile.xslt
- create output a.htm
- modify, save myfile.xslt
- create output b.htm
- compare A.htm and B.htm to see the effect of the modified xslt

Sometimes I did the same with modified XML.

**Comment by lovettchris** [comment]
Yeah, comparing 2 outpus.  I see.  That's a good scenario to support, I'll remove the clever "cleanup" code that turns out to be not so clever... :-)

**Comment by Pierre-de-la-Verre** [comment]
Still active in version 2.8.0.61

**Comment by lovettchris** [comment]
Fixed in 2.8.0.62
