### ISSUE TITLE
How does this relate to the software on microsoft.com?

### ISSUE THREAD

**Issue by AnthonyMastrean** [Microsoft/XmlNotepad#2]
#Is this the latest version of this software? Will updated versions ever be posted to microsoft.com (it's currently reporting v2.5)?

https://www.microsoft.com/en-us/download/details.aspx?id=7973

**Comment by lovettchris** [comment]
Yes, The [downloadable installer](http://www.lovettsoftware.com/downloads/xmlnotepad/readme.htm) is the latest version.  I'm trying to remove the old version on microsoft.com, but it is taking some time...

**Comment by AnthonyMastrean** [comment]
Thanks! We can close this ticket or leave it open as a reminder about that microsoft.com link ;)
