### ISSUE TITLE
Usability topic: name of program in dialogue title

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#201]
Closing the software shows (when necessary) this dialogue:
![grafik](https://user-images.githubusercontent.com/13277944/167406408-faba7b63-21c9-421e-a17d-3bcdb0429473.png)
My problem is sometimes - closing different programs at the same time brings up the question: 
Which software is talking to me?
When you add the name of the program to the dialogue it would be clear.

**Comment by lovettchris** [comment]
Fixed in commit #748cf824cb6c06457ca923529d4abedf24bfdc6c
![image](https://user-images.githubusercontent.com/18707114/168388733-8d42be61-61c9-4045-b1c5-4de03fd2cf7c.png)

**Comment by clovett** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.60
