### ISSUE TITLE
Find up - problems with longer strings

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#203]
It seems that the program has problems with "find: up" when the containing string is rather long (or when it contains the search string more than once or both of it). It stops at the same position - no progress, no error. "Find: down" is no problem. See attached screencast where I modified and used your"hamlet"

https://user-images.githubusercontent.com/13277944/167639606-17957a83-1c41-48ef-a943-cbfcbfb96a29.mp4

.

**Comment by lovettchris** [comment]
Thanks for the great bug and excellent video explaining, this is fixed in https://github.com/microsoft/XmlNotepad/commit/32fe6d504ab1ca63659f34e890211a3155a04ea7

**Comment by clovett** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.60
