### ISSUE TITLE
XMLNotepad 2.8.0.27 -  21H2 Compatible

### ISSUE THREAD

**Issue by lafrancisco** [microsoft/XmlNotepad#205]
Does anyone know if XML Notepad v 2.8.0.27 is windows 21H2 compatible

**Comment by lovettchris** [comment]
Yep, also works on Windows 11, but I would recommend the latest version of XML notepad which is 2.8.0.59

![image](https://user-images.githubusercontent.com/18707114/168140201-8758ffab-f348-4be0-942e-37397c782548.png)

**Comment by lafrancisco** [comment]
Thank you!!!!



Lori Iadevaia-Francisco
Manager, Application Development
CapAbilities CRG – Business & Operations Lead
CapAbilities Community Outreach
CVS Community Ambassador
Security Ambassador

***@***.***
Office: 401-770-3064  | 1 CVS Drive, Mail Drop 1180, Woonsocket, RI 02895 | ***@***.******@***.***>
***@***.***


Security Ambassador

Visit Global Security Awareness
for the latest security news and alerts.
CVS<https://mylife.cvshealth.com/webcenter/portal/mylife/Departments/BusinessTechnology/iss/SecurityAwareness> / Aetna<https://aetna.unily.com/sites/information-security-infosec/SitePage/344074/home>



CONFIDENTIALITY NOTICE: This communication and any attachments may contain confidential and/or privileged information for the use of the designated recipients named above.  If you are not the intended recipient, you are hereby notified that you have received this communication in error and that any review, disclosure, dissemination, distribution or copying of it or its contents is prohibited.  If you have received this communication in error, please notify the sender immediately by telephone and destroy all copies of this communication and any attachments.



From: Chris Lovett ***@***.***>
Sent: Thursday, May 12, 2022 2:06 PM
To: microsoft/XmlNotepad ***@***.***>
Cc: Francisco, Lori A. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/XmlNotepad] XMLNotepad http://2.8.0.27 - 21H2 Compatible (Issue #205)

**** External Email - Use Caution ****
________________________________
Yep, also works on Windows 11, but I would recommend the latest version of XML notepad which is 2.8.0.59<http://2.8.0.59>

[Image removed by sender. image]<https://user-images.githubusercontent.com/18707114/168140201-8758ffab-f348-4be0-942e-37397c782548.png>
