### ISSUE TITLE
Link to Internet Explorer

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#206]
The standard text in XSL Output begins with:

Your XML document contains no xml-stylesheet processing instruction. To provide an [XSLT transform](https://www.tutorialspoint.com/xslt/index.htm), add the following to the top of your file and edit the href attribute accordingly: <?xml-stylesheet type="text/xsl" href="stylesheet.xsl" ?>

The ink behind "XSLT transform" opens Internet Explorer, although I use another browser. My settings or standard behaviour?

**Comment by lovettchris** [comment]
I fixed this in version 2.8.0.61, but you have to first install the [WebView2 ](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) component.  Then in the WebView2  component the link to the XSLT transform (or anything other links you output in your XSLT) will honor your system default web browser setting.

**Comment by Pierre-de-la-Verre** [comment]
Does not work for me.
- I have 2.8.0.61
- tried to install WebView2. It says "already installed".
- still calls Internet Explorer

**Comment by lovettchris** [comment]
You may also need to change the Web Browser Version setting under Options to WebView2:

![image](https://user-images.githubusercontent.com/18707114/180849836-cfff04af-f489-46bd-a493-120661fb0c37.png)

**Comment by Pierre-de-la-Verre** [comment]
> You may also need to change the Web Browser Version setting under Options to WebView2:

Thanks. Works fine
