### ISSUE TITLE
"Search feature" in TreeView and XSLOutput

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#212]
TreeView and XSLOutput have different search functions. That's OK, but changing the tab does is not honored by the dialogue.

Example:
- Open Tree View
- search something
- change to XSL Output
- the search dialogue stays in foreground and active
- click "search": it searches and finds in TreeView, while you are still watching the XSL Output

I think a dependency between tabs and displayed search dialogues would be fine.

**Comment by lovettchris** [comment]
Great bug, yes I think the easiest fix is to auto-hide the search dialogue when you select the XSLT output tab.

**Comment by lovettchris** [comment]
I pushed a fix for this.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.3
