### ISSUE TITLE
Error when loading XML file

### ISSUE THREAD

**Issue by stevebow** [microsoft/XmlNotepad#214]
Using XN 2.8.0.61 standalone version.

I have tried to load a movie subtitle file that is in XML format (attached as zip file) - although the file appears to be a HTML file?  Anyway, on loading, an error dialog is displayed per the attached image.  When loaded into a text editor, there is a "&" character at the indicated position.  Is this actually in violation of the XML specification?

Also, the dialog indicates the error as at position 19 - if it is the ampersand character that is the problem, this is actually at position  18.

In XN, at the bottom of the screen there is a section with 2 tabs: Error List , Dynamic Help.  Shouldn't XN at least attempt to load the XML file and so provide information in the Error List?  Additionally, in the View menu it is possible to go to Next Error - again supporting that XN should be loading problematic files to be able to use this function?  Currently (per the attached dialog image) I can either send the file to a text editor, or do nothing when clicking No.

Thanks,
Steve

![XNP Error](https://user-images.githubusercontent.com/20422753/181648854-a2bd16a7-c286-4195-b844-2972d23fbcf0.png)
[01 The Conjuring - Horror 2013 English.zip](https://github.com/microsoft/XmlNotepad/files/9214630/01.The.Conjuring.-.Horror.2013.English.zip)

**Comment by lovettchris** [comment]
XML Notepad does not try and auto-fix XML files, but you can rename your .xml file to .htm then use the File/Open menu to open it as HTML and then it will auto-fix the unescaped ampersand character:

![image](https://user-images.githubusercontent.com/18707114/181821143-34c9b92b-6912-4501-b2d5-fe3e6a597730.png)

**Comment by stevebow** [comment]
No problem, thanks.
