### ISSUE TITLE
Customize Window Title

### ISSUE THREAD

**Issue by benclaussen1** [microsoft/XmlNotepad#219]
Feature suggestion: 

I often have multiple XML files open and in the taskbar I only see a portion of the file path/name:

![image](https://user-images.githubusercontent.com/46791633/185662335-984a250d-e7bd-4917-b74b-f39d1ae55199.png)

Can we get an option to possibly remove "XML Notepad" or display path/filename only? In _my_ case, I would need "filename only" since the location of the files is buried and I would likely not see it anyway.

Thanks so much!

**Comment by lovettchris** [comment]
The relative font size difference between your title bar and the contents of XML Notepad seems very different from my computer:

![image](https://user-images.githubusercontent.com/18707114/189251719-5b101593-2bd6-4866-aced-393a8f826d97.png)

Did you do something on your system to customize your Window titlebar appearance?  The reason I ask is I'm wondering if I can somehow programmatically detect what is going on there so I can automatically truncate the titlebar contents only when necessary.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.63
