### ISSUE TITLE
Request to support xalan external xslt

### ISSUE THREAD

**Issue by jriobello** [microsoft/XmlNotepad#223]
Hi,

Consider including a call to the xalan processor from the tool.
Configure path to xalan command. See: https://xml.apache.org/xalan-j/commandline.html

This utility can be used for xalan or other transformation processes external to the tool.

**Comment by lovettchris** [comment]
It is unlikely that XML Notepad will be integrated with xalan-j but if there are specific features of xalan-j  that you wish XML Notepad's [XSLT feature](https://microsoft.github.io/XmlNotepad/#help/xslt/) please list them here, thanks.

**Comment by jriobello** [comment]
I Chris,

I have xslt using xalan namespace (xmlns:xalan="http://xml.apache.org/xalan")
, but xml notepad xslt not working:
"No script or extension object associated with namespace '
http://xml.apache.org/xalan' could be found."

In XML Spy, you can use alternate xslt processor to resolve this.
i need migrate my xslt from xalan to msxml parser?

Thank you in advanced

**Comment by lovettchris** [comment]
Yeah, ok, integration with xalan is difficult since it is a Java platform.  XML Notepad is .NET based.  So this is a 'won't fix", sorry.
