### ISSUE TITLE
How to find Tag+Content?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#225]
I want to search and find for the string "<ID>1539", because searching only for 1539 brings too many unwanted results. In an texteditor it is no problem, but how to make it in XmlNotepad?

**Comment by lovettchris** [comment]
I don't follow.  Can you give more info, perhaps a screen shot of the XML Notepad find dialog you are trying to do and an example XML file that returns too many unwanted results?  The XML Notepad find dialog does allow you to limit what is being searched better than the text editor does, for example, the Search Filter allows you to limit what it looks inside of:
![image](https://user-images.githubusercontent.com/18707114/196518037-6bf76e53-0b2f-4b2e-875f-b69872c5b22c.png)

**Comment by Pierre-de-la-Verre** [comment]
Hi Chris
maybe I'm doing nonsense, but here my example: An XML with this structure:

```
...
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <id>1234</id>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
  <Parent_ID>1234</Parent_ID>
...
```

I want to find "<i>1234". Searching for "1234" brings too much results (all the <Parent_ID> ..), searching for <"<id>1234" brings no result:
![grafik](https://user-images.githubusercontent.com/13277944/196659275-dd3d9dcd-5538-4d70-8b74-d68009eb724c.png)

**Comment by lovettchris** [comment]
Ah, you need to learn XPath syntax, but if you click on the text in the id element in the treeview, then Ctrl+F then click the "Use XPath" button it will show you what the xpath expression is for finding that node.  Then you can edit the xpath expression to find others, for example try "//id/1234".  See https://riptutorial.com/xpath/example/6209/find-all-elements-with-certain-text.

**Comment by Pierre-de-la-Verre** [comment]
Thanks, Chris
as expected is the problem on the front side of the keyboard.
