### ISSUE TITLE
How to "Got to line number 1234"?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#226]
I now that XML is not "thinking" in lines, but sometimes I have the same XML opened in XMLNotepad and in a pure texteditor where I know that my cursor is now in line number 1234. 
It would be nice (but not the most important thing) to have a feature for "Goto Line number xy" too.

**Comment by lovettchris** [comment]
nice idea.

**Comment by lovettchris** [comment]
I added Ctrl+G in this pull request in case you want to try it out:

https://github.com/microsoft/XmlNotepad/pull/251

**Comment by Pierre-de-la-Verre** [comment]
Hi Chris
is there a link to download the msi / exe / .. ?
I don't know how to use these Githb features..

**Comment by lovettchris** [comment]
[XmlNotepad.zip](https://github.com/microsoft/XmlNotepad/files/10525267/XmlNotepad.zip)

I uploaded a zip file right here in this comment.  Let me know how it goes, thanks.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.0
