### ISSUE TITLE
Line Command to automatize XMLNotepad 

### ISSUE THREAD

**Issue by arcangelomolinaro** [microsoft/XmlNotepad#23]
Is it possible in the near future to have some command line like Open, Close, Load, etc. Etc. to automate the use of the software in a batch file or other use ?
Tia
Arcangelo

**Comment by yonetch** [comment]
I agree. I want this to replace the command msxsl.exe. Because I want to use XInclude.

**Comment by yonetch** [comment]
I agree. I want to use this command in substitution for msxsl.exe. Because it does not support XInclude.

**Comment by lovettchris** [comment]
A command line editor for XML sounds great but this is outside the scope of XML Notepad.
