### ISSUE TITLE
Strange behaviour of "find" command

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#232]
Hi Chris
I know my knowledge is limited, but this behaviour seem to be not correct:
Screencast: https://autode.sk/3gqk5QU

**Comment by lovettchris** [comment]
Excellent test, and repro video, thanks.  I have pushed a fix, it will be included in the next version.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.0
