### ISSUE TITLE
Standalone install link from wiki returns a 404

### ISSUE THREAD

**Issue by paillave** [microsoft/XmlNotepad#25]
In the wiki (https://github.com/Microsoft/XmlNotepad/wiki), the link that permits to download the standalone installer (http://www.lovettsoftware.com/downloads/xmlnotepad/xmlnotepadsetup.zip) is broken; it returns a 404. Where to download it?

**Comment by lovettchris** [comment]
Can you try downloading this file and tell me if it works for you as a standalone installer? [http://lovettsoftware.com/downloads/xmlnotepad/setup.exe](http://lovettsoftware.com/downloads/xmlnotepad/setup.exe)

**Comment by paillave** [comment]
I don't know if it's an old habit or not, but I always prefer getting the full setup on my computer rather than dealing with a clickonce. I just like to know that I can access any of my tools (even if not installed yet) in case of no internet connection. In the case of xmlnotepad, the exe is at a more convenient place if I want to make an "open with" on a file that doesn't have the right extension. I know, nothing 100% rational... it's mainly a matter of feeling... I guess I'm getting old :)

**Comment by micrat** [comment]
Hello, please update standalone installer (http://www.lovettsoftware.com/downloads/xmlnotepad/xmlnotepadsetup.zip) to release 2.7.1.21. Thanks in advance

**Comment by lovettchris** [comment]
done.
