### ISSUE TITLE
Using XSLT Transformation with commandline?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#250]
Is there a chance to use XSLT Transformation with commandline?

Like "xmlnotepad.exe myinput.xml mydefintion.xslt myoutput.csv" ?

**Comment by lovettchris** [comment]
I have a command line xslt tool here: https://github.com/clovett/tools/tree/master/xsl

**Comment by Pierre-de-la-Verre** [comment]
Same problem here - I know only to download Exes, but no idea to compile ...

**Comment by lovettchris** [comment]
I put a zip file here that contains the built binaries.

https://github.com/clovett/tools/releases/tag/v1.0

**Comment by Pierre-de-la-Verre** [comment]
Thanks, Chris
I got it.
