### ISSUE TITLE
Copy path of an element to clipboard

### ISSUE THREAD

**Issue by VincentD21** [microsoft/XmlNotepad#258]
Hi,

is there an option to copy only the path of an element to the clipboard and not the whole element structure itself?

Otherwise, is it possible to implement this feature?

Thanks in advance,
Vincent

**Comment by lovettchris** [comment]
One way to find the path to the selected element is to use the [Find Dialog with 'Use XPath'](https://microsoft.github.io/XmlNotepad/#help/find/) then copy the path that shows up in the "find what" field.

**Comment by VincentD21** [comment]
Thanks for the quick reply. This works for me.
