### ISSUE TITLE
Shopee 

### ISSUE THREAD

**Issue by masuktik** [microsoft/XmlNotepad#260]
"url": "https://shopee.com.my/",
              "label": "Malaysia"
            },
            {
              "subLinks": [],
              "url": "https://shopee.sg/",
              "label": "Singapore"
            },
            {
              "subLinks": [],
              "url": "https://shopee.com.br/",
              "label": "Brazil"
            },
            {
              "subLinks": [],
              "url": "https://shopee.com.mx/",
              "label": "Mexico"
            },
            {
              "subLinks": [],
              "url": "https://shopee.com.co/",
              "label": "Colombia"
            },
            {
              "subLinks": [],
              "url": "https://shopee.cl/",
              "label": "Chile"
            },
            {
              "subLinks": [],
              "url": "https://shopee.pl/",
              "label": "Poland"
            }
          ],
          "active": false,
          "name": "default"
        }
      ]
    },
    "tabNavigation": {
      "active": false,
      "tabMenus": [],
      "tabSelectionConfig": []
    },
    "androidShowOfflinePage": true,
    "iosShowOfflinePage": true,
    "toolbarNavigation": {
      "enabled": false,
      "visibilityByPages": "allPages",
      "visibilityByBackButton": "backButtonActive",
      "regexes": [
        {
          "enabled": true,
          "regex": ".*"
        }
      ],
      "items": [
        {
          "system": "back",
          "titleType": "defaultText",
          "visibility": "allPages",
          "urlRegex": [
            {
              "enabled": true,
              "regex": ".*"
            }
          ]
        },
        {
          "system": "refresh",
          "enabled": false,
          "visibility": "allPages",
          "urlRegex": [
            {
              "enabled": true,
              "regex": ".*"
            }
          ]
        },
        {
          "system": "forward",
          "enabled": false,
          "titleType": "defaultText",
          "visibility": "allPages",
          "urlRegex": [
            {
              "enabled": true,
              "regex": ".*"
            }
          ]
        }
      ]
    },
    "iosOfflinePageHtml": "",
    "androidOfflinePageHtml": "",
    "offlinePageHtml": ""
  },
  "styling": {
    "iosLaunchScreen": {
      "backgroundImage": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182495_bfwgj3v1uuqa8_FFFFFF_1_2x2.png",
      "backgroundImageDark": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182495_gbq1qhcbtzne6_000000_1_2x2.png",
      "backgroundColor": "#FFFFFF",
      "backgroundColorDark": "#000000",
      "centerImage": "https://s3.amazonaws.com/gonativeio/images_generated/cx8b1j1j0ydc8_1676359049308.png",
      "centerImageDark": "https://s3.amazonaws.com/gonativeio/images_generated/cx8b1j1j0ydc8_1676359049308.png"
    },
    "transitionInteractiveDelayMax": 0.2,
    "menuAnimationDuration": 0.15,
    "iosTheme": "default",
    "androidLaunchImages": {
      "mdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182733_f3c3njay2n2ew_180x180.9.png",
      "hdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182733_t0a3fchtj64c2_270x270.9.png",
      "xhdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182733_u1b39h9acrgh4_360x360.9.png",
      "xxhdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182733_jwdy7p4npw846_540x540.9.png",
      "xxxhdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182733_j463q3ygvq8d4_720x720.9.png"
    },
    "androidLaunchImagesDark": {
      "mdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182734_4jvn5ejp6cqvm_180x180.9.png",
      "hdpi": "https://s3.amazonaws.com/gonativeio/images_generated/1676359182734_m2v4atcx55wm4_270x270.9.png",

**Comment by lovettchris** [comment]
This question makes no sense.
