### ISSUE TITLE
Please add customization of colors for xml diff output html page

### ISSUE THREAD

**Issue by LeonxPRO** [microsoft/XmlNotepad#268]
Please add customization of colors for xml diff output html page

**Comment by lovettchris** [comment]
Version 2.9.0.7 will give you a way to "open XmlDiff styles" in notepad.exe so you can edit them, this is a rudamentary way to give you what you want here and assumes you are comfortable editing .css files.

**Comment by lovettchris** [comment]
[Release 2.9.0.7 ](https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.7) is now available.
