### ISSUE TITLE
error in stylesheet location

### ISSUE THREAD

**Issue by micrat** [Microsoft/XmlNotepad#28]
I just updated from 2.7.1.16 to 2.7.1.20: I encontuered the following bug: the stylesheet URL defined in the XML seems to be searched in the C:/ drive instead of the real web location.

![immagine](https://user-images.githubusercontent.com/15943390/52125244-21438380-262c-11e9-9073-fd97a3360dbe.png)

In the 2.7.1.16 I'm able to view the same XML with its stylesheet without any problem.
Thank you

**Comment by lovettchris** [comment]
woops, fixed in 2.7.1.21
