### ISSUE TITLE
Do not run scripts from Temp folder

### ISSUE THREAD

**Issue by christophvw** [microsoft/XmlNotepad#280]
Please do not run scripts from Temp folder:
%OSDRIVE%\USERS\USERNAME\APPDATA\LOCAL\TEMP\XMLNOTEPAD\STATS.CMD

This will be blocked by proper a AppLocker config.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.2
