### ISSUE TITLE
Great, this project is still being updated

### ISSUE THREAD

**Issue by pizixie** [microsoft/XmlNotepad#283]
I used this tool many years ago, and I was surprised to see the release here today

**Comment by lovettchris** [comment]
# 😊

yeah, we have too many users and downloads to just walk away, and a pretty cool community of folks proposing some really fun pull requests.  It is fun to see the app being used all over the planet:

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/81e40f83-f788-41d4-8c7b-dc166bdc8964)

Rock on!

**Comment by WilczynskiT** [comment]
Which app you use to track this activity? It is screen from Google Analytics?

**Comment by lovettchris** [comment]
yes it is google analytics.
