### ISSUE TITLE
XSD association fails

### ISSUE THREAD

**Issue by Bukran** [microsoft/XmlNotepad#289]
I've just installed XmlNotepad on my new laptop and I'm having trouble to associate it to open xsd extension.
There hasn't been any problem with xml but the system ignores XmlNotepad when selecting "open with..." in XSD. I'm not even able to find XmlNotepad.exe file to manually select it.

I've tried ClickOnce installer, then uninstalled, then tried with winget. I think am walking around with no success.

![Snapshot1](https://github.com/microsoft/XmlNotepad/assets/12096727/c685b3c3-797d-433e-99a9-625c52a51c25)
![Snapshot2](https://github.com/microsoft/XmlNotepad/assets/12096727/d2c24c1c-6e46-4689-abde-d31029f6c055)

**Comment by lovettchris** [comment]
I made a video for you showing how to do it:
https://youtu.be/n-6sSUSlN34

**Comment by Bukran** [comment]
That was great. Thank you very much.
I've had managed to associate it but now it has also set the proper icon.
