### ISSUE TITLE
Invalid Rex file. the requested value 'Ins' could not be located

### ISSUE THREAD

**Issue by Saija** [microsoft/XmlNotepad#31]
I just downloaded the repository as a zip, unzippped, open it on Visual Studio 2017 Community and there appears this error message(among others): 

"No se puede encontrar el valor solicitado 'Ins'. línea 401, posición 5."

C:\Users\MyUser\Desktop\XmlNotepad-master\src\XmlNotepad\FormMain.resx	

línea 401, posición 5(Line 401, pos 5)

Sorry, my locale is Spanish, see title of this issue for a translation

![2019-02-26 17_48_18-xmlnotepad - microsoft visual studio](https://user-images.githubusercontent.com/5026125/53452277-d7fa1000-39ee-11e9-86ed-d7e4bb4cc2d6.jpg)

**Comment by lovettchris** [comment]
Interesting, I think I would need a Spanish system to fix this.   Any luck on your side finding a fix for this?

**Comment by lovettchris** [comment]
This should be fixed now, let me know if you still see the problem, thanks.
