### ISSUE TITLE
Incomplete schema validation of large XML files ( > ~20 MB)

### ISSUE THREAD

**Issue by AikenBM** [microsoft/XmlNotepad#329]
I'm using XML Notepad 2.9.0.5 on Windows 10 Enterprise 22H2 19045.3208.

I've discovered that XML Notepad's validation gives up around the 20 MB mark. The application will end with displaying a line number a column number of `0` in the error list. The program will then stop validating any further schema errors.

I am attaching a zipped 42 MB XML file that contains 100 schema validation errors. This example uses sample data from the state of Michigan's Department of Education state reporting system because that's what I was doing when I found the problem.

[SchemaErrors.zip](https://github.com/microsoft/XmlNotepad/files/12229005/SchemaErrors.zip)

XML Notepad validates and identifies the first 43 or so errors, but the last one listed doesn't appear to populate the table the same way, and it stops after that error. Even exporting the list doesn't show the remaining errors. Here's a screenshot of the error list:

![image](https://github.com/microsoft/XmlNotepad/assets/31443007/87c92719-8a3a-4d04-9c10-08a28a93f6eb)

Based on my incidental testing, any schema validation error after roughly the 20 millionth character or 565,000th line in the file will fail in this way. Only the first error in that range will show, in the error list, and the error list will not display accurate information. I don't see any setting in the application's options to increase this apparent limitation.

I've also included the following Powershell function below which uses `System.Xml.XmlReader` to validate the schema, and it correctly identifies all 100 schema errors.

```
function Validate-XmlFile {
    [CmdletBinding()]
    param (
        # The path to the XML file
        [Parameter(Mandatory = $true, Position = 0)]
        [String]
        $Path,

        # Instead of outputing the warnings, just return true if valid and false if invalid
        [Switch]
        $IsValid,

        # Force the process to download the schema again instead of potentially using a cached version
        [Switch]
        $ForceSchemaRefresh
    )

    process {
        $XmlFileName = Get-Item $Path -ErrorAction Stop

        $XmlReaderSettings = New-Object -TypeName System.Xml.XmlReaderSettings
        $XmlReaderSettings.ValidationType = [System.Xml.ValidationType]::Schema
        $XmlReaderSettings.ValidationFlags = ([System.Xml.Schema.XmlSchemaValidationFlags]::ProcessInlineSchema -bor
            [System.Xml.Schema.XmlSchemaValidationFlags]::ProcessSchemaLocation -bor
            [System.Xml.Schema.XmlSchemaValidationFlags]::ReportValidationWarnings -bor
            [System.Xml.Schema.XmlSchemaValidationFlags]::ProcessIdentityConstraints)

        $XmlUrlResolver = [System.Xml.XmlUrlResolver]::new()
        # Some versions of Powershell require credentials. Use anonymous credentials to satisfy the class.
        $XmlUrlResolver.Credentials = [System.Net.NetworkCredential]::new('anonymous','anonymous@example.com')
        $XmlUrlResolver.CachePolicy = [System.Net.Cache.RequestCacheLevel]::Revalidate
        if ($true -eq $ForceSchemaRefresh) {
            $XmlUrlResolver.CachePolicy = [System.Net.Cache.RequestCacheLevel]::Reload
        }
        $XmlReaderSettings.XmlResolver = $XmlUrlResolver

        # Create the validation handler to capture the validation errors and warnings
        $script:ValidationOutput = [System.Collections.Generic.List[String]]::new()
        $ValidationEventHandler = [System.Xml.Schema.ValidationEventHandler] {
            # $_ is the second argument of type System.Xml.ValidationEventArgs
            $script:ValidationOutput.Add(("{0} on line {2}: {1}" -f $_.Severity, $_.Message, $_.Exception.LineNumber))
        }
        $XmlReaderSettings.add_ValidationEventHandler($ValidationEventHandler)

        try {
            $XmlReader = [System.Xml.XmlReader]::Create($XmlFileName.FullName, $XmlReaderSettings);
            [System.Xml.XmlDocument]::new().Load($XmlReader)
            $XmlReader.Dispose()
            if (!$IsValid) {
                if ($script:ValidationOutput.Count -eq 0) {
                    Write-Host "No validation errors in file '$($XmlFileName.FullName)'."
                }
                else {
                    # Write-Host "Validation errors written to '$ValidationErrorFile'"
                    # $script:ValidationOutput | Set-Content -Path $ValidationErrorFile -Encoding ascii
                    $script:ValidationOutput
                    Write-Warning ("{0:n0} errors detected in '{1}'" -f $script:ValidationOutput.Count, $XmlFileName.FullName)
                }
            }
            else {
                if ($script:ValidationOutput.Count -eq 0) {
                    return $true
                }
                else {
                    return $false
                }
            }
        }
        finally {
            $XmlReader.Dispose()
        }
    }
}
```

Note that I typically use Powershell v7.3 with the above function. I'm not sure if it still works with Windows Powershell v5.1.

**Comment by lovettchris** [comment]
Very excellent bug report, I'll check it out, thanks.

**Comment by gitnol** [comment]
I want to add, that schema validation within xml notepad below 0x20 is not correct or seems not to fully work as been defined here: https://www.w3.org/TR/2006/REC-xml-20060816/#NT-Char
Char	   ::=   	#x9 | #xA | #xD | **[#x20-#xD7FF]** | [#xE000-#xFFFD] | [#x10000-#x10FFFF]	/* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. */

i had a file in which 0xE; was found:
&#xE;	26 23 78 45 3B   	-> https://en.wikipedia.org/wiki/Shift_Out_and_Shift_In_characters
![image](https://github.com/microsoft/XmlNotepad/assets/2466699/e1e71620-2ce0-4741-8cd4-d336dbc86ffa)

but the character 0x1F; (US = Unit Separator) was not found invalid in the same file
&#x1F;	26 23 78 31 46 3B	-> https://en.wikipedia.org/wiki/C0_and_C1_control_codes#Field_separators
![image](https://github.com/microsoft/XmlNotepad/assets/2466699/2429338f-e75e-4270-8908-9e3bffc54bd9)

I hope this helps fixing the schema validation

**Comment by clovett** [comment]
Ok, I did some investigation and found that what you are hitting here is a limit in the number of nodes indexed for line/column information so the schema errors can be linked to the specific line/col.  This limit was set to 1,000,000 which your file exceeds with 1130401 nodes.  I'm adding a new option in the options dialog that allows you to increase this limit:

![image](https://github.com/user-attachments/assets/2f111aa9-9e26-4e15-9ae0-11842970a240)

You'll know this limit was reached if you see validation errors with a line/col = 0, which you do see in your case at the end of the error list.

**Comment by clovett** [comment]
I also found and fixed the illegal character check:

![image](https://github.com/user-attachments/assets/d3830941-7c67-4f0b-8104-cc665d90c871)

**Comment by lovettchris** [comment]
These are fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.14
