### ISSUE TITLE
"Replace" with unallowed characters

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#331]
I started a "Replace" like "replace 'earth' with 'hello world'" and pressed "replace all". Then I got the correct message that a blank is not allowed.
![xmlnotepad](https://github.com/microsoft/XmlNotepad/assets/13277944/40744d4e-3ff6-4be1-9d7a-040898cc9d42)
The "problem" is - because of "Replace all" it doesn't stop the command, it comes gain and again with the same message, and there is no comfortable way to stop it.
Maybe - as third priority - this could be improved.

**Comment by lovettchris** [comment]
Thanks for the bug report, this is bad, can you attach an XML file that reproduces this bug also? Thanks.

**Comment by Pierre-de-la-Verre** [comment]
Hi Chris
you can take your "Hamlet" and replace "TITLE" with "my title". It seems that is starts to replace and then it brings the message:
![grafik](https://github.com/microsoft/XmlNotepad/assets/13277944/78352fd9-33f0-4eed-a567-1e98ecbc34e4)

**Comment by lovettchris** [comment]
will be fixed in 2.9.0.6
