### ISSUE TITLE
XML Comparison report doesn't show full path of file being compared 

### ISSUE THREAD

**Issue by SeanKilleen** [microsoft/XmlNotepad#332]
Stumbled across this tool and used it to compare XML files quickly and correctly. Thanks for the time saver! 

I noticed that in the HTML output of the comparison report, the file we're comparing to doesn't appear to be listed -- just its directory. Screenshot:

> ![image](https://github.com/microsoft/XmlNotepad/assets/2148318/9a25f94e-1658-4582-939c-646e5aeeb7d5)

I think it's because the XmlDiffBody resource string is defined as: 

https://github.com/microsoft/XmlNotepad/blob/67e13a2a77c5be3e951fc7918cea3854190ec8a4/src/XmlNotepad/StringResources.resx#L456-L460

And when called, the directory is what's passed to it:

https://github.com/microsoft/XmlNotepad/blob/67e13a2a77c5be3e951fc7918cea3854190ec8a4/src/Application/FormMain.cs#L2527-L2532

This is just a drive-by issue so I haven't gotten to look into it deeply but figured I'd start by passing it along.

**Comment by lovettchris** [comment]
Thanks for the bug report.

**Comment by lovettchris** [comment]
File in editor : {1} is correct, this is picking up sourceXmlFile which is a full path.

Maybe this is fixed in a newer version because this is what I'm seeing:

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/a289157e-7173-41f1-9515-58f4666ace2f)
