### ISSUE TITLE
can not open  in VS 2017

### ISSUE THREAD

**Issue by soberj** [microsoft/XmlNotepad#34]
hello,
  there   always    exits a  error that  
“"E:\Anik\Work  Files\XMLeditor\srcc\PublishDrop.cmd" "E:\Anik\Work  Files\XMLeditor\srcc\Application\bin\Debug\" > "E:\Anik\Work  Files\XMLeditor\srcc\Publish.log"
”已退出，代码为 4。	Application			生成

**Comment by lovettchris** [comment]
Hmmm, can you attach the Publish.log file that is created? All the script is trying to do is copy files to the ~\Application\bin\Debug folder, the binaries and help files.  It might fail if some of those files are locked?

**Comment by lovettchris** [comment]
I fixed this bug.  I was due to the "spaces" in your file path there.
