### ISSUE TITLE
Download "Standalone 2.9.0.6"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#341]
Hi
both from https://microsoft.github.io/XmlNotepad/#install/  and https://github.com/microsoft/XmlNotepad I get an error for downloading the ZIP. Could you check it please?

**Comment by lovettchris** [comment]
Sorry about that should be fixed now.

PS: You can also get the zip file from https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.6
