### ISSUE TITLE
Crash upon launching

### ISSUE THREAD

**Issue by cmartel2** [microsoft/XmlNotepad#357]
Despite uninstalling and reinstalling more than once, XML Notepad either crashes upon launching, or crashes when trying to open an XML file (I've tried drag and drop, using the Open file, or using the Open with directly from the file directory).

**Comment by lovettchris** [comment]
Sorry to hear that, can you tell me which installer you used? ClickOnce, Standalone or winget?

Also XML Notepad now depends on [.NET Framework 4.8](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48) can you make sure you have that version installed?

If the crash provides any popup message or details can you include that information also, thanks.

**Comment by cmartel2** [comment]
I have tried both the ClickOnce and the Standalone. And the .NET Framework 4.8 is installed.

Unfortunately, there are no pop up messages or details to provide! The app just closes.

**Comment by lovettchris** [comment]
That's unfortunate.  You could try deleting these files if they exist:
- C:\Users\<your user name>\AppData\Roaming\Microsoft\Xml Notepad\XmlNotepad.settings
- C:\Users\<your user name>\AppData\Local\Microsoft\Xml Notepad\XmlNotepad.settings

Last time I saw anything like this it seemed to be related to windows defender not recognizing my signing certificate and booting the app out for that reason.  More likely if you are running on a machine that is managed by a corporation.  If you are familiar with the [Windows Event Viewer](https://www.windowscentral.com/how-use-event-viewer-windows-10) and if you can find any relevant errors there that might be helpful.  If you are a developer and you can launch the app in the Visual Studio debugger and find the load time exception that would be super helpful.

**Comment by cmartel2** [comment]
I am indeed on a corporate machine. I will reach out to IT as soon as my workload decreases a bit to see if I can troubleshoot with them, using the information that you have provided so far. Thank you!

**Comment by lovettchris** [comment]
Ok, good luck.

**Comment by lovettchris** [comment]
Great, I have not used it with box, but when I point it to a file on a One Drive folder it works.  Does Box have a concept of "keep files on this device" that you could try to force Box to pre-download the files before trying to open them in XML Notepad?

**Comment by lovettchris** [comment]
I just installed [Box Drive for window](https://www.box.com/resources/downloads) and it shows my Box account as a new windows drive, and I put the XML notepad samples up there.  
![image](https://github.com/microsoft/XmlNotepad/assets/18707114/78f8354a-b8ce-4acf-b6ff-dbb0d93ceecc)

I was then able to double click the xml files and open them in XML notepad:
![image](https://github.com/microsoft/XmlNotepad/assets/18707114/e8cd4727-fca8-4840-8b73-d2863705c101)

I could also shift+right+click a file and select "Copy as path" and paste that into the XML notepad address bar and open files from my Box folder that way:
![image](https://github.com/microsoft/XmlNotepad/assets/18707114/c26199aa-884c-4e21-9538-17b813c2ac75)

So can you try following these steps?
