### ISSUE TITLE
Xml file can be opened for viewing/editing, but not compared

### ISSUE THREAD

**Issue by shadolight** [microsoft/XmlNotepad#36]
Reduced test case. Open 'a.xml' with this content:
```xml
<?xml version="1.0" ?>
<First>
<Second>
<x>&#32;</x>
</Second>
<y>5</y>
</First>
```
Compare with this 'b.xml' wit this content:
```xml
<?xml version="1.0" ?>
<First>
<Second>
<x>&#32;</x>
</Second>
<y>6</y>
</First>
```
If there are any difference between the 2 files (the y element in this case) it will error with a "Length cannot be less than zero. Parameter name: length". 

This is actually caused by the 'hex encoded' space character in the x element.

**Comment by lovettchris** [comment]
Thanks for the awesome repro.  I merged your fix for this.  Thanks for the contribution to improving XML Notepad!
