### ISSUE TITLE
Function to print files

### ISSUE THREAD

**Issue by Thommy7571** [microsoft/XmlNotepad#369]
Hallo, your tool is superbe. No other tool of this type compares to it, since it shows the ressources, the structure and the output of the file. Others permit only to see the structure or only the output or show nothing at all, if ressources are missing...  I would appreciate the possibility to print an XML-file from the menue as a pdf or a picture - as multipage document or single  pages document.  I made the observation that for some strange reason some color disappeared from the original file when prining it to pdf otherwise..  Also, I would much apprechiate if it was possible to open by defaut the output page instead of the "edit page".  That is what is need more than to modify it. Perhaps a new version in view of Win 10 should get out?

**Comment by lovettchris** [comment]
Actually if you just want to print the XSLT output page you can type CTRL+P to invoke the print function on the embedded web browser panel and you will see this:

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/e94aa001-f4ac-4c7e-94ce-9c4600ae15d2)

If you then pick the PDF printer you will get your pdf file.  If it is a big pdf it may take a while to complete, the file size will be 0 until it is done, but then you will be able to load it and view it like this:

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/40dd78bd-2953-4e50-bb67-cfe7d84e12d2)

Does this suffice?
