### ISSUE TITLE
Error Message after SEARCHING and drag&drop of a new file

### ISSUE THREAD

**Issue by JAF84** [microsoft/XmlNotepad#370]
hello,

i'm using V2.8.0.61.

Please try to open an XML file and use the "FIND" funktion and search for something which is in the XML file.
leave the FIND window open.

now use drag&drop to open an other xml file.

then you will get an error message like this, see screenshot.

![grafik](https://github.com/microsoft/XmlNotepad/assets/25920439/cd45e48c-c95c-42bf-ad54-a2abf5197876)

can you reproduce this issue?
br johannes

**Comment by lovettchris** [comment]
Great bug, thanks, I have a fix that will be included in the next release.
