### ISSUE TITLE
Multiple instances resets the settings

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#381]
When I open some instances of XMLNotepad, they all use the xmlnotepad.settings. But when I close the instances, some settings are reset to standard value, especially the group of "XMLDiff-settings" and my standard texteditor.
I suppose that the refreshing of the settings with "last used files" creates this issue.

**Comment by lovettchris** [comment]
Hmmm, interesting problem, are you closing lots of windows all at once?  I wonder if one is writing while the other is trying to and clobbering the file, causing errors then reverting the file to defaults as a result.  if so I will have to think of a solution to this problem... In the meantime giving each one a good second or so before closing might help avoid this issue, let me know if that helps.

**Comment by Pierre-de-la-Verre** [comment]
I think it's not a time problem, it's an "Option" problem:
- open File a.xtf (session a)
- View - Options: it's OK
- open file b.xtf (session b)
- View - Option: it's OK
- close session b
- in Session 1: View - Options: -> changed to standard settings

**Comment by lovettchris** [comment]
Great bug, it was a problem in how settings were getting reloaded, this is fixed in https://github.com/microsoft/XmlNotepad/commit/e698427cecf6a3b8e4709b7c8b2a04a6a0279fab and will be in the next update.,

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.9
