### ISSUE TITLE
Sugg: Clear message for long XSLT-Transform

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#382]
When I start a XSLT-transform with e.g. 50MB input, then I see ..
- at first nothing
- then a turning sandclock
- "(not responding)" as additional information in the program title
- heavy load on my CPU-monitor
and I don't know if the software is dead or not ...

So if you add a message / dialogue / status bar info or something else with
" Started transformation on 11:34:23, wait until final message" ....
the user will now what is going on.

Chris - have a fine weekend!

**Comment by lovettchris** [comment]
Great suggestion, thanks.

**Comment by lovettchris** [comment]
I added a progress dialog with a cancel button in [these commits](https://github.com/microsoft/XmlNotepad/commit/6021f198222d2e012d1baaf9901fcbb53b739864) and [this one](https://github.com/microsoft/XmlNotepad/commit/2cf651d42588eeee23ff8c05a75e29c0aa6037ce) in case you want to try it:

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/6dc1641c-099a-4971-8c30-8e1951057433)

The progress only pops up if it takes more than 1 second and the cancel is not perfect, the cancel can only cancel when the transform starts reading input or writing output, but I notice some transforms spend a lot of time doing calculations internally before writing anything so you can still see a pause between the time you try and cancel and when it actually cancels.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.9
