### ISSUE TITLE
Reload of a "not loaded" file

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#383]
I try to open a file with errors, it reports ...

> "Error loading: ... Would you like to open it using your text editor?"

That's OK, I click  "No" and modify the XML. When saving, XMLNotepad asks me:

> "File Changed. The file you are editing ... Would you like to reload?"

That's a fine feature, but unexpected ... - if it is not loaded in step a) it can not be **re**loaded in step b). It's not clear that the file is in a kind of "Waiting loop". A small information would help to see the user what's happening ..

**Comment by lovettchris** [comment]
Good bug, fixed by https://github.com/microsoft/XmlNotepad/commit/102f3238f20e99769ba7d2a2b4b24d936a524bd4 and will be in the next update.

**Comment by lovettchris** [comment]
Fixed in https://github.com/microsoft/XmlNotepad/releases/tag/2.9.0.9
