### ISSUE TITLE
Will this application ever be released as an MSI again?

### ISSUE THREAD

**Issue by AnthonyMastrean** [Microsoft/XmlNotepad#4]
In fact, I'm not sure I see any packaging/installer code checked in... (I've forgotten how ClickOnce manifests are maintained, I might just be missing it).

**Comment by lovettchris** [comment]
The clickonce info is in [this project file](https://github.com/Microsoft/XmlNotepad/blob/master/src/Application/Application.csproj).

**Comment by AnthonyMastrean** [comment]
Got it. Still curious about the MSI (even a portable ZIP would be preferable). I'm interested in updating the Chocolatey package and MSI and ZIP files play nicer with package managers.

https://chocolatey.org/packages/xmlnotepad

**Comment by lovettchris** [comment]
I see, how's this ?

https://github.com/Microsoft/XmlNotepad/releases/tag/v2.7

**Comment by AnthonyMastrean** [comment]
Beautiful :)

**Comment by lovettchris** [comment]
Great!
