### ISSUE TITLE
Standalone downloadable installer missing from repo?

### ISSUE THREAD

**Issue by greiginsydney** [microsoft/XmlNotepad#40]
The [readme.md](https://github.com/microsoft/XmlNotepad/blob/master/readme.md) references a "Standalone downloadable installer" but I can't find it in the repo. Has it fallen out?

- G.

**Comment by lovettchris** [comment]
It is not checked into git hub [lives here](http://www.lovettsoftware.com/downloads/xmlnotepad/xmlnotepadsetup.zip).

**Comment by greiginsydney** [comment]
Thanks Chris, my mistake. :-(
