### ISSUE TITLE
Copy to clipboard hangs on large files

### ISSUE THREAD

**Issue by pavelbraginskiy** [microsoft/XmlNotepad#407]
When trying to copy a node from a large XML file (the one I was editing, attached below, is around 28MB) with ctrl+c, XmlNotepad stops responding. For all I know it will eventually finish the operation, but I terminated it after several minutes. 

All other operations on the file that I tried worked fine, with delays of maybe a couple seconds at worst.

[system_events.zip](https://github.com/user-attachments/files/16698329/system_events.zip)

**Comment by pavelbraginskiy** [comment]
I should mention this happens even if the individual node I'm trying to copy is tiny. 
If I tried to copy the entire document, the hang would be more understandable.

**Comment by lovettchris** [comment]
sounds like a bug, thanks for the report.

**Comment by clovett** [comment]
I found the problem, working on a fix.
