### ISSUE TITLE
Suggestion: please limit "Check for Update"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#413]
I have activated "Check for Update" and open the software again and again - and it is checked again and again. So please make a limitation ..
- fixed to once a day / once a week or
- selectable via an option.

Have a good time!

**Comment by lovettchris** [comment]
There is an update frequency in the default updates.xml file at https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/Updates.xml which is set to 1 day.  But I will add an option so you can override this.

**Comment by Pierre-de-la-Verre** [comment]
Works fine now. Thanks.
