### ISSUE TITLE
Suggestion: add an area for free text

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#414]
I played around with some text-snippets, copy&paste, saving the value from the "xpath-copy" and so on - and I had to open my text editor to handle all my small-snippet-stuff.

So maybe you could add a small "text editor area / function" to XMLNotepad? Just a quick idea, not first priority ..

**Comment by lovettchris** [comment]
Nice idea, but out of scope for xml notepad.  How about you use "window/newwindow" and add a new root element named "clipboard", then copy paste snippets into this "clipboard" document as needed ?
