### ISSUE TITLE
"Updates.xml" is outdated

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#415]
I just loaded the current version 2.9.0.11 from today, but the Updates.xml is from April 2024 and version 2.9.0.9.
Maybe that's the reason that the tooltip on the green field "up to date" tells me "your version is 2.9.0.9 "

**Comment by Bavarello** [comment]
![Immagine 2024-09-20 203047](https://github.com/user-attachments/assets/1df4df1c-874f-4ae0-a2a1-922d004c5b30)

**Comment by lovettchris** [comment]
Hmmm, can you do File/Open Settings and copy the UpdateLocation URL and paste it here?  I'm curious where it is looking for the updates.xml file...

**Comment by lovettchris** [comment]
Fixed https://lovettsoftwarestorage.blob.core.windows.net/downloads/XmlNotepad/Updates.xml now contains the latest version.  Not sure what happened before, my publish.cmd script should have updated it.  I simply ran it again and now it's up to date and I published v2.9.0.12 which contains the new feature of [Generate xml from schema](https://microsoft.github.io/XmlNotepad/#help/schemas/).
