### ISSUE TITLE
Expand (right mouse) / expand all - problems with scrolling

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#416]
I could not nail this behaviour to the latest detail, but ..

- when I use "Expand" on the right-mouse-contextmenu it happens that I could not scroll anymore in the structure tree.
I attach a screencast and an example file (modified from your updates.xml) and I wonder if someone who can confirm this. Maybe you have to

- expand the tree
- collapse it with click on the -button
- use context menu

(the "not scrolling command" is not seen on the screencast, but always when nothing happens I try to scroll .. ;-) )
[test.zip](https://github.com/user-attachments/files/17072854/test.zip)
![xmlnotepad_scrolling](https://github.com/user-attachments/assets/e3d81f86-8476-42f2-90d2-7125083e5c14)

**Comment by lovettchris** [comment]
Yes I can see the problem, thanks I'm investigating. So far it looks like there might be some sort of .net change in how the mouse wheel event is being generated.

**Comment by clovett** [comment]
I pushed a possible fix, and could not repro your excellent example, if you can build the binary from master branch yourself please give it a bash, if all is good I'll publish a new version.

**Comment by Pierre-de-la-Verre** [comment]
Sorry, but I never compiled something. For me it would be better when you create the exe.

**Comment by Pierre-de-la-Verre** [comment]
Oh, oh - I think that's my bad. I had set "XmlNotepad.settings" to read-only, and after changing this it seem to work fine.
Very sorry for this "wrong alert".

**Comment by clovett** [comment]
Ok, I published version 2.9.0.13.
