### ISSUE TITLE
Smaaaaall cosmetic topics ..

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#417]
Last priority ..

![grafik](https://github.com/user-attachments/assets/e73088f7-890c-4790-82e5-af47c337a24a)

![grafik](https://github.com/user-attachments/assets/1addc6a1-ae85-4b17-8cec-58f711f8c07b)

![grafik](https://github.com/user-attachments/assets/f013305b-6a47-4f91-acbe-2b58016840cc)

**Comment by clovett** [comment]
Thanks, these fixes will be included in the next version.
