### ISSUE TITLE
Different shakespear output ...

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#422]
I took your samples Hamlet.xml and willy.xsl and made a transformation with
- XMLNotepad 2.9.0.13 and
- xsl.exe from clovett from Jan. 2023

The transformed output is nearly the same but differs in some line-breaks. What's the reason for this?

**Comment by clovett** [comment]
I see.  With preserve whitespace enabled I seem to get better results if I add this new template after the first template:

  <xsl:template match="P">
    <xsl:value-of select="text()" />
  </xsl:template>

I'm not sure why this makes a difference.  But after adding this template XML notepad now produces this HTML output:

```html
    <center>
      <h1>The Tragedy of Hamlet, Prince of Denmark</h1>
      <p>
        <h2>William Shakespeare</h2>
      </p>
    </center>The Tragedy of Hamlet, Prince of Denmark
    ASCII text placed in the public domain by Moby Lexical Tools, 1992.
    SGML markup by Jon Bosak, 1992-1994.
    XML version by Jon Bosak, 1996-1999.
    The XML markup in this version is Copyright © 1999 Jon Bosak.
This work may freely be distributed on condition that it not be
modified or altered in any way.
```

**Comment by clovett** [comment]
If you want an XSLT that can also work properly without preserve whitespace you can instead add the following 2 templates to the bottom of your stylesheet:

```xml
<xsl:template match="P">
    <xsl:value-of select="text()" /><span>&#xA0;</span>
</xsl:template>
<xsl:template match="TITLE">
    <xsl:value-of select="text()" /><span>.&#xA0;</span>
</xsl:template>
```
I might push this one to the repo since it works better.

**Comment by Pierre-de-la-Verre** [comment]
Thanks, Chris,
it will be helpful for some other users too.
