### ISSUE TITLE
Windows 11 24H2 compability?

### ISSUE THREAD

**Issue by SMGot01** [microsoft/XmlNotepad#426]
Hi there.

Is XML Notepad running without issues in Windows 11 24H2 specifically?

We will migrate to 24H2 next year and will start testing our application portfolio in December.

Kind regards
Anders Pålsson

System Specialist
Göteborgs Stad, Sweden

**Comment by Jvr2022** [comment]
Hi there @SMGot01!

I have windows insider program on 24h2 and it runs without bugs.

So if you want to upgrade to 24h2 it is possible 

Greetings Jvr2022

**Comment by SMGot01** [comment]
Great news!
Much appreciated.  :-)

**Comment by Jvr2022** [comment]
@lovettchris this can be closed
