### ISSUE TITLE
More File Types

### ISSUE THREAD

**Issue by BreadAndEggs** [microsoft/XmlNotepad#427]
XML Notepad should have more file types than XML, there should be 

JSON
NBT
YAML
CSV
INI
TOML
CBOR
Avro
Parquet
Feather
FlatBuffers
BSON
HDF5
SQLite Database File
RDF
SAS
XSD

**Comment by lovettchris** [comment]
ha ha, great list.  It certainly can open and edit XSD files already and it can import .csv and .json files too.  Note the XML Notepad file open dialog has this drop down showing supported file types:

![Image](https://github.com/user-attachments/assets/78e0b9eb-4005-4281-a745-3f220c4db693)

**Comment by BreadAndEggs** [comment]
You should add nbt because minecraft mainly uses nbt,

**Comment by BreadAndEggs** [comment]
You should create a code maker that uses GUI to make code in a lot of languages, c, c#, c++, python,  swift, and more! it will make code editing so much easier
