### ISSUE TITLE
XmlDiffView api for DifferencesAsFormattedText locks up source file as a result after diff operation the source file cannot be deleted

### ISSUE THREAD

**Issue by githubajay1mishra** [microsoft/XmlNotepad#44]

**Comment by lovettchris** [comment]
fixed in version 2.8.0.8.

**Comment by githubajay1mishra** [comment]
I merged  changes for the fixes and tried out the fixes for version 2.8.0.8.
The issue still exists.

**Comment by lovettchris** [comment]
Please provide exact repro steps then.  I tested loading a file, doing a diff, and checking I could delete both files, and that works with the latest version.

**Comment by lovettchris** [comment]
closed due to inactivity, please reopen if you see this again and add some steps I an follow to see the same bug.
