### ISSUE TITLE
Error parsing EntityName if file contains the "&" symbol

### ISSUE THREAD

**Issue by lfa4** [microsoft/XmlNotepad#47]
An error has occurred while parsing EntityName. Line 1244, position 45. 
Would you like to open using Notepad?

[Silverado.zip](https://github.com/microsoft/XmlNotepad/files/4237692/Silverado.zip)

I am attempting to alter mods for a game and any mod containing the "&" symbol is giving me this error.

**Comment by lfa4** [comment]
sorry forgot to mention, using version 2.8.0.7 and removing the & symbol from within the file removes the error.

**Comment by lovettchris** [comment]
See XML specification : https://www.w3.org/TR/REC-xml/#syntax

The "&" character cannot be written without escaping it to the special character entity reference &amp;

Similarly "<" has to be written &lt;

and so on.

**Comment by lfa4** [comment]
heh, so the game recognizes it as part of a text string but it isn't proper xml format.  tyvm for the info.

**Comment by lovettchris** [comment]
Correct.  XML has a stricter format than HTML and it is designed that way to ensure that when programs consume XML there is no ambiguity about the exact content in the XML document.

**Comment by lfa4** [comment]
and them some goofy game dev had to break the rules, lol.  it's ok, i'll just change all the &'s to and because i really like using your progam's interface :D

thanks again

**Comment by lovettchris** [comment]
yes that can happen a lot when developers think they can write code that generates XML, but they don't use a proper XML generation library.  When that happens they usually get it wrong.  The .NET Framworks provide [System.Xml](https://docs.microsoft.com/en-us/dotnet/api/system.xml?view=netframework-4.8) for this purpose.  And that's the same library that XML notepad uses.
