### ISSUE TITLE
Break out XmlDiffPatch/View as official NuGet packages

### ISSUE THREAD

**Issue by phatcher** [microsoft/XmlNotepad#48]
There's only an unofficial NuGet package based on the original NET 1.1 version of the code and although json is taking over the world, there's still a lot of XML in enterprise applications that needs supporting.

Extract out XmlDiffPatch and XmlDiffView as separate NuGet packages and also support NET Core,

BTW I don't mind taking a first attempt at this.

**Comment by lovettchris** [comment]
Good idea, I just submitted a commit that prepares for this and an XmlDiff.nuspec in XmlDiffView folder builds a package.  Unfortunately, nuget.org is currently not letting me publish it with this name, not sure why, so I'm finding out.

**Comment by phatcher** [comment]
Has a quick look at the nuspec and can I suggest going down to .NET 4 and 4.5.2 if it's possible so that people can adopt it without upgrading frameworks - I know we're all supposed to be on 4.8/NetStandard 2.0 but some companies/industries can be slower to change ;-)

**Comment by lovettchris** [comment]
done.

**Comment by lovettchris** [comment]
I contacted the owner of https://www.nuget.org/packages/XMLDiffPatch/1.0.8.28, to see if I can just update that library, we'll see if I get a response...

**Comment by phatcher** [comment]
Cool, I was just updating some OS projects I worked on in 2014 and was trying to avoid having to do this bit of the work :-)

**Comment by lovettchris** [comment]
Owner didn't respond so I posted it to Nuget under a different name:
See [https://www.nuget.org/packages/LovettSoftware.XmlDiff/1.0.0](https://www.nuget.org/packages/LovettSoftware.XmlDiff/1.0.0).

**Comment by phatcher** [comment]
Thanks, I'll have a play
