### ISSUE TITLE
Colors for white areas

### ISSUE THREAD

**Issue by lucknaumann** [microsoft/XmlNotepad#49]
Thanks for this program!
I was wondering if the background of the main viewing area could also have color changes like the other elements. As you can see from the image the areas to the right of elements aren't colored like the rest of the backgrounds. And also the bottom panel "Description" (basically all the white areas).
Thanks.
![XMLNotepad](https://user-images.githubusercontent.com/51302763/79287919-1c0dd580-7e7a-11ea-977d-691dca073002.PNG)

**Comment by lovettchris** [comment]
Yep, in fact I added a new "Color Theme" setting with defaults for "Light" and "Dark" theme, with these colors by default.  I also redid the icons so they are transparent.

![image](https://user-images.githubusercontent.com/18707114/83342437-50134d80-a2a4-11ea-8180-07d4c8719057.png)

**Comment by lucknaumann** [comment]
Wow! That looks great! You rock!! Thanks! =)
