### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by evanshultz** [Microsoft/XmlNotepad#5]
Is it possible to make a portable version of XmlNotepad, rather than one that needs to be installed?

**Comment by lovettchris** [comment]
So you want a version that is installed using the Windows Store app ?

**Comment by evanshultz** [comment]
No, a portable version that runs without an installer. Just click the file and the app launches. I haven't looked at the code but I've done that with other simple .NET apps.

**Comment by lovettchris** [comment]
Ah, you want an all in one XmlNotepad.exe with no separate DLL's that need to be installed... right?

**Comment by evanshultz** [comment]
Yes, sir. Maybe it's not realistic, but a fella can ask(?).

**Comment by lovettchris** [comment]
I won't have time to do this.
