### ISSUE TITLE
Problem opening files from network

### ISSUE THREAD

**Issue by ghendric** [microsoft/XmlNotepad#56]
I'm having a problem opening xml from a network location if the url has spaces in it. I remember there being a registry hack to fix that but I can't remember what registry key to edit. Basically, i need to put " around it.. Do you what the registry key is?

Thanks

**Comment by lovettchris** [comment]
Hmmm, I don't, but try replacing the space with %20 and see if that helps...

**Comment by lovettchris** [comment]
I did a test here and it loaded fine, note you have to use the address bar not the File/Open dialog like this:

![image](https://user-images.githubusercontent.com/18707114/108321884-9c2b5880-7179-11eb-970a-6bb50a1dede3.png)

The File/Open dialog is a Windows feature and Windows downloads the file and caches it locally, which breaks any references to external schemas or XSLT stylesheets.

**Comment by ghendric** [comment]
It didnt work if I double clicked the file from windows explorer to open it from a network location instead of a mapped drive to a network location. If that makes sense..I typically set xml notepad as the default app to open XML files

**Comment by lovettchris** [comment]
Can you tell me more about how you are setting up a windows explorable "network location" ?

**Comment by lovettchris** [comment]
I also tried this and it worked fine, so I'm closing this for now, please reopen if you can provide a good clear set of steps that reproduce the bug, thanks.

![image](https://github.com/microsoft/XmlNotepad/assets/18707114/59963e31-9e4f-44b2-a203-0e005a420338)
