### ISSUE TITLE
Size of dropdown list with previously opened files

### ISSUE THREAD

**Issue by qupear** [microsoft/XmlNotepad#57]
There is a dropdown list which contain previously opened files. But it is limited by 10 items. It will be 
 useful to have scrollbar or an option to specify a number of items in this dropdown list. If this is possible could you add this to config?

**Comment by lovettchris** [comment]
Great suggestion, I fixed the menu so it has a history of 20 and the dropdown combo location box now has a history of 1000, I also enabled auto-completion in the combobox so as you type the list is automatically filtered to show matching file names.   Hopefully these changes make the history more useful.  This is fix is available in version 2.8.012.

**Comment by qupear** [comment]
Thank you very much, much better now.
