### ISSUE TITLE
XML files stored on Sharepoint won't open

### ISSUE THREAD

**Issue by gerdami** [Microsoft/XmlNotepad#6]
Whenever I open an XML file stored on SharePoint Server 2013, I get a Load Error message:
Invalid URI: The hostname could not be parsed. Would you like to open it using Notepad? Yes/No.

**Comment by clovett** [comment]
I'm not sure how you get a direct link to a file on sharepoint so I don't know how to test this.  What I do instead use the sharepoint "sync" feature to create local sync'd copy of sharepoint files, and XML Notepad can open the files from there no problem.  Does this work for you?

**Comment by gerdami** [comment]
Thanks for reply.
From a SharePoint library, I "Open with Explorer" from the "Connect and Export" group from the ribbon, then double click on the file or drop it into XML Notepad (versions 2.5 or 2.7.1).
It seems that the Sync feature has been disabled by our organization.

**Comment by clovett** [comment]
I can repro the problem, looking into it, thanks.

**Comment by gerdami** [comment]
My IT department got the same issue with VB.NET. 
The standard .NET library for loading an XML file from a filename (XmlDocument.Load) via webdav was causing this error as soon the filename contained the @SSL because of the https.
The code snippet that worked for us, i.e. use the LoadXml instead of the Load, is shown below:
`    ''' <summary>
    ''' Load XMLDocument with handling for failure because of WebDav UNC path containing @SSL
    ''' Other exceptions are not handled
    ''' </summary>
    Public Shared Function LoadXmlDocument(fullname As String) As XmlDocument
        Dim result As XmlDocument = New XmlDocument

        Try
            result.Load(fullname)
        Catch ex As UriFormatException
            ' Load may fail (Invalid URI: The hostname could not be parsed. for SharePoint WebDav UNC path containing @SSL)
            ' Second try via load XML
            result.LoadXml(File.ReadAllText(fullname))
        End Try

        Return result
    End Function
`
I hope it helps.

**Comment by gerdami** [comment]
Well, it didn't help :-(

**Comment by lovettchris** [comment]
I found that Notepad and other apps could note open share point files either, they get a weird guestaccess.aspx instead.   There is probably a way to do this using the [Microsoft Graph API](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/onedrive).  But that will take some work.  In the meantime, you can request the "Sync" from your sharepoint admin so you can sync a local folder, then XML Notepad can open the file from there.

**Comment by lovettchris** [comment]
I won't have time to implement this.  Someone else is welcome to try and submit a pull request.
