### ISSUE TITLE
Naming of applicationSettings My.MySettings setting

### ISSUE THREAD

**Issue by qupear** [microsoft/XmlNotepad#60]
This is a feature suggestion. So in .config files we have big applicationSettings section with a lot of setting items. Right now in "xml notepad" it looks like on the screenshot. What I am suggesting is getting a value of name attribute of the setting item and then in the Tree View either substitute string "setting" with the value of name either append value of name to string "setting". With that being implemented it will be much easier to look for specific setting without remembering exact position and without using View - Expand All menu button.
![image](https://user-images.githubusercontent.com/8069685/90428847-42b07700-e0cd-11ea-89b5-3c09729dea62.png)

**Comment by bimimicah** [comment]
+1 Support.
We have a great use case for this feature too, **specifically for a customizable version (map a different attribute to each element)**:
![image](https://user-images.githubusercontent.com/34111930/90640161-a3d76800-e1fd-11ea-9088-9f6552157e6f.png)
Example usage:
![image](https://user-images.githubusercontent.com/34111930/90641205-f2d1cd00-e1fe-11ea-821d-09061b125117.png)

**Comment by lovettchris** [comment]
Yes, all good suggestions - I would call this a "Schema aware" Tree View where important "key" elements are lifted from the children of an element to better identify that element in the tree...

**Comment by WilczynskiT** [comment]
Added and waits for your review @lovettchris  ;)
The result:
![Screenshot 2023-05-11 105726 lnk](https://github.com/microsoft/XmlNotepad/assets/102859171/0c08044c-a968-4003-af5a-d4d03bf21b14)

**Comment by WilczynskiT** [comment]
@qupear It was added
