### ISSUE TITLE
Cannot easily assign associate to xml

### ISSUE THREAD

**Issue by slestak** [microsoft/XmlNotepad#62]
With the new W10 associate by filetype ui, XMLNotepad is not a choice.  Not even a browse ability to the filesystem.

![Annotation 2020-08-31 145040](https://user-images.githubusercontent.com/79189/91755623-6974b000-eb99-11ea-8b5c-41f9e64a56cc.png)

**Comment by lovettchris** [comment]
See if this helps:
https://github.com/microsoft/XmlNotepad/issues/50

**Comment by slestak** [comment]
That is still a workaround correct?  I would hope that is not the norm.

**Comment by lovettchris** [comment]
Well, editing the registry requires admin permissions, and XML notepad is installed in a way that does not have admin permissions, so I'd have to bundle a separate "installer" app with XML notepad that XML notepad launches on user request which then asked for elevated permission, then if the user clicks yes, only then can it make these changes to your system.  It could be done, but it's tricky...

**Comment by slestak** [comment]
I don't think we are trying to get the association done during the install. I think the crux is getting xmlNotepad chooseable in the list.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lovettchris** [comment]
Right in that case I would argue your feature/bug request is for the Windows shell team :-) I'm not sure why an app that's actually running on your machine doesn't show up in the list of apps you can select for associating file types.  Note this is a fairly recent change too - it used to show up there.

**Comment by bimimicah** [comment]
Just a note, hope you find it helpful:
Per-machine installs should create a ProgID (e.g. `XMLNotepad.xmlfile`) under:
`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\`
And then register the ProgID under:
`HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.xml\OpenWithProgIds`

**Per-user installs would do the same, just replace `HKEY_LOCAL_MACHINE` with `HKEY_CURRENT_USER`** Example:
`HKEY_CURRENT_USER\SOFTWARE\Classes\XMLNotepad.xmlfile`
`HKEY_CURRENT_USER\SOFTWARE\Classes\.xml\OpenWithProgIds -> XMLNotepad.xmlfile`

This reference may be useful: [`https://docs.microsoft.com/en-us/windows/win32/shell/fa-file-types`](https://docs.microsoft.com/en-us/windows/win32/shell/fa-file-types)

On my machine, for example:
![fileProgIDhandlers](https://user-images.githubusercontent.com/34111930/91905309-584ca180-ec74-11ea-80ff-babc849e300f.PNG)

**Comment by lovettchris** [comment]
Thanks man, that was super useful, you are right, I can at least setup the XmlNotepad.xmlfile progi in HKEY_CURRENT_USER, then the user can do the rest using windows explorer or the default apps settings dialog.  I pushed a fix in 2.8.0.17 where the "View/File Associations" menu item now sets this up correctly, so you can right click an .xml file and XML notepad is listed there:

![image](https://user-images.githubusercontent.com/18707114/91929409-2a2a8a00-ec93-11ea-8fc5-762e612d10bb.png)
