### ISSUE TITLE
Download links dead

### ISSUE THREAD

**Issue by dmenne** [microsoft/XmlNotepad#66]
Download links of click-once and standalone installers are dead.

**Comment by lovettchris** [comment]
Can you try this one http://lovettsoftware.com/downloads/xmlnotepad/xmlnotepadsetup.zip

**Comment by dmenne** [comment]
Thanks. I found it via Google anyway, but the link on the github mainpage is still dead.

**Comment by clovett** [comment]
Oh, I found this one is dead:
[Windows MSIX installer](http://www.lovettsoftware.com/downloads/XmlNotepad.Net/index.html) if you need a trusted Windows installer.

But not this one:
[Standalone downloadable installer](http://www.lovettsoftware.com/downloads/xmlnotepad/xmlnotepadsetup.zip) if you need something that works offline.

I fixed the MSIX link, thanks.

**Comment by lovettchris** [comment]
Should be fixed now.
