### ISSUE TITLE
SimpleGoogleAnalytics dll not found

### ISSUE THREAD

**Issue by buckleyGI** [microsoft/XmlNotepad#67]
I download XML notepad v 2.8.0.23 from https://microsoft.github.io/XmlNotepad/##handy-features-include

It works well but when I start it I get this error. If you click it away XML notepad will start fine.

![image](https://user-images.githubusercontent.com/2102864/107340290-df246680-6abd-11eb-8972-c068e939a33f.png)

**Comment by buckleyGI** [comment]
Correction, the program was not usable as it threw exceptions while executing.

I used the click once version and that works.
The problem seems to be wit the standalone installer.

**Comment by clovett** [comment]
Thanks for the but report I published a new version that adds the missing dependencies, thanks.

**Comment by lovettchris** [comment]
Should be fixed now.
