### ISSUE TITLE
Homepage shows version ...18.. in title

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#68]
but software is already at ...23....

**Comment by lovettchris** [comment]
This is the home page and I see no version there: https://microsoft.github.io/XmlNotepad/

But I did find an old version here http://lovettsoftware.com/downloads/xmlnotepad/readme.htm -- this is not really the home page, it is just a landing page for the clickonce installer.  I switched this page to become the clickonce generated publish.htm page so it should remain up to date from now on.

**Comment by Pierre-de-la-Verre** [comment]
> But I did find an old version here http://lovettsoftware.com/downloads/xmlnotepad/readme.htm -- ...

Yes, this is what I meant. It's up to date now - thanks.
