### ISSUE TITLE
Suggestion: Avoid compare with itself

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#69]
It's is user-based problem, but it would be nice to avoid it via software:
I open c:\text.xml and want to compare it with another XML. but I'm confused and select c:\text.xml again ... - now the software starts comparison and shows a message that the "content" is the same (instead of reporting the "file itself" is the same

**Comment by lovettchris** [comment]
Fixed in 2.8.0.24.
