### ISSUE TITLE
Latest download release does not match github version.

### ISSUE THREAD

**Issue by ivan-kljajic** [microsoft/XmlNotepad#73]
Hello. I installed XML Notepad for the first time on my computer yesterday, and see that version 2.8.0.26 was downloaded and installed. But your releases page reports the latest version as 2.8.0.25. Do your binary releases get from the latest source and not the latest published released version, or are they modified from the source release version to contain some extra code?
Sorry if there is a faq about this somewhere.

**Comment by lovettchris** [comment]
Thanks for the report, so yes 2.8.0.26 is the latest version.

Where are you seeing 2.8.0.25 mentioned?

**Comment by ivan-kljajic** [comment]
Hi, I see it on the main GitHub project page Releases section, and on the project releases page it is the top entry labeled "Latest Release". [https://github.com/microsoft/XmlNotepad/releases](https://github.com/microsoft/XmlNotepad/releases).

**Comment by ivan-kljajic** [comment]
![xmln](https://user-images.githubusercontent.com/56899869/112250366-5ba98800-8cad-11eb-8d2b-33e86ce8b4a2.png)

**Comment by lovettchris** [comment]
Oh right, yeah, I've been remiss in keeping github releases up to day.  Fixed now:
https://github.com/microsoft/XmlNotepad/releases/tag/2.8.0.27

**Comment by ivan-kljajic** [comment]
No worries. Thanks.
