### ISSUE TITLE
Compare XML: Missing information in header

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#75]
Version 2.8.0.13 (and also in 2.8.0.26)
This is the header of the XML-compare-output:
![grafik](https://user-images.githubusercontent.com/13277944/112335036-2eb0a180-8cbc-11eb-9c3d-76f2401e633d.png)
The left file informations shows only the file, not the path. The right info shows only the path, not the file.
Bug or feature?

**Comment by lovettchris** [comment]
Will be fixed in next version, code change is committed:
https://github.com/microsoft/XmlNotepad/commit/863d9ca41952f61182add9540a1228cc947a2603

**Comment by Pierre-de-la-Verre** [comment]
Fixed in 2.8.0.28
