### ISSUE TITLE
"stats.cmd" as UTF-8 with BOM (more cosmetics)

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#76]
I started the command "View - Statistics" and got this result:
![grafik](https://user-images.githubusercontent.com/13277944/112343928-e4332300-8cc3-11eb-8ab0-9b10a6b5a5db.png)

(In English: Comamnd "...echo" is wrong written or could not be found)
Maybe it is caused by the reason that "stats.cmd" is UTF-8 with BOM?
The statistics itself works fine without display problems.

**Comment by lovettchris** [comment]
fixed in version 2.8.0.27

**Comment by Pierre-de-la-Verre** [comment]
Thanks, works fine.
