### ISSUE TITLE
Compare XML: colours for "moved from / to"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#80]
The legend shows two fields "moved from" / "moved too" with the same colour. I don't understand the idea behind it. 

- Does it really mean "moved from A to B" then there is the question: is A always left and B right? Then it would need one colour for left and one for right.
- Or does it mean: I found code-segments X and Y and Z which are identical on left and right side, but on a different position? Then it would need different colours for X-segment and for Y-segment and for Z-segment .. (- looks rather hard to solve)
- Or does it means: All these segments are identical, but moved? Then it would need only one field "identical, but moved"

But maybe I'm totally lost ..

**Comment by lovettchris** [comment]
The 3rd option.  It means you can visually see the blocks that moved by matching colors:

![image](https://user-images.githubusercontent.com/18707114/112535552-ac7eb680-8d69-11eb-9174-97beb9cbf9c3.png)

**Comment by Pierre-de-la-Verre** [comment]
So what do you think about "one field "identical, but moved""?

**Comment by lovettchris** [comment]
ok, but this requires change to XmlDiff nuget package, so I'll bundle this minor fix next time XmlDiff needs a bigger update.

**Comment by lovettchris** [comment]
I'm closing this for now, since I thought about it some more and I think the blue implies "identical".
