### ISSUE TITLE
"Check for update" - no message for no update

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#81]
The "Check for update" gives no message when no update is found. The user does not know: No updates or no function?
It could display something like "No updates available".

**Comment by lovettchris** [comment]
Good point, this will be fixed in the next release, the code change is pushed already here: 
https://github.com/microsoft/XmlNotepad/commit/9e7eaba2404838a8eb201a2c4431c48789fabe68

**Comment by Pierre-de-la-Verre** [comment]
Added in 2.8.0.28
