### ISSUE TITLE
Feature request: allow portable usage

### ISSUE THREAD

**Issue by thomazz-nl** [microsoft/XmlNotepad#86]
Sadly XmlNotepad is pushed with all kinds of installers, while some people prefer their programs and tools to be portable. Taking the .cab content of the offline installer gives me a working portable program, except that it still loads and saves the settings to the user's local appdata.

Feature request: change the [ConfigFile getter](https://github.com/microsoft/XmlNotepad/blob/9d490e4f9831780f83e53185a6fbe23b54874b42/src/XmlNotepad/FormMain.cs#L2570) to check if the file XmlNotepad.settings exists in the same directory as the program's main executable, if it does: save and return the file's path (use those settings). If it does not: proceed as usual.

**Comment by lovettchris** [comment]
I've very much against promoting the distribution of unprotected executables.  That's how viruses spread.  And installer with cryptographic signature that is verified on install ensures that the bits you are installing have not been tampered with.  But of course, if you control the bits and you are just copying them across your machines, perhaps sharing them on your personal private one drive folders then fine I understand that scenario also.

Looking for the config file where it finds the binary is fine, but then I'd also have to check if that folder is write protected (like Program Files) and then still copy that to the users local appdata, is that what you had in mind?

**Comment by thomazz-nl** [comment]
Hi Chris, thanks for the feedback. I understand your concerns keeping the distributions as safe as possible. Adding a "unprotected" binary release would be a "nice to have" for me, but I'll be fine without one too. I quoted unprotected, because having a signature is no guarantee for safe software. Checking a SHA1 hash of a .zip release supplied by the author is equally effective and is used by many software creators. With or without signature or hash, safety is never guaranteed: I believe [CCleaner](https://www.ccleaner.com/knowledge/security-notification-for-ccleaner-v5336162-and-ccleaner-cloud-v1073191-for-32-bit-windows-users) was a signed program too when it was distributed including malware. Although XML Notepad seems like software for tech-savvy users, I do agree that for common users a installer is most likely the best choice.

The change you suggest sounds good: I hadn't thought about the write-ability check on saving the settings. Adding a fallback to the user's local appdata makes perfect sense.

The use-case is indeed as you described: taking a personalized copy of XML Notepad either on a USB stick or (in my case) placing it on a cloud share (NAS) with my applications that I selectively sync to my devices. This way I only need to update an application once instead of on multiple devices. On top of that my settings are in sync without having to rely on individual programs to support Microsoft's syncing of settings.

**Comment by lovettchris** [comment]
Will be fixed in version 2.8.0.30.
See commit https://github.com/microsoft/XmlNotepad/commit/5c7389e7a0ad3727cbf95a8adccb9f8fce3d94ae

**Comment by thomazz-nl** [comment]
Works like a charm Chris, thanks a bunch!

**Comment by lovettchris** [comment]
You're welcome and thanks for the suggestion.
