### ISSUE TITLE
Feature Request: "Select file .. " for XSLT output

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#88]
Wouldn't it be fine to have a "Select file ..." button for the XSLT Output too?
![grafik](https://user-images.githubusercontent.com/13277944/115555930-5e999780-a2b0-11eb-916b-d52f3c23160d.png)

**Comment by lovettchris** [comment]
Good idea, fixed in 2.8.0.30

**Comment by Pierre-de-la-Verre** [comment]
added in 2.8.0.30
