### ISSUE TITLE
Immediate / unwanted output of "Transform"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#89]
When I open files like "C:\Program Files (x86)\LovettSoftware\XmlNotepad\Samples\rss.xml", it creates immediately the file "rsspretty_output.htm" in my <Temp>.

I'm not sure - is this a good or a bad behaviour?
Usually (for me) a software with a GUI displays the output at first step on screen, and only the second step - the "transform / save as .." command - creates a file.

So is this a standard behaviour?

**Comment by lovettchris** [comment]
I agree it is unusual, but it is hard to change, the XSLT rendering you see is currently dependent on running the XSLT transform and producing a file, that file is then loaded into a web browser and you see the result.  This architecture makes it hard to change, unless the XSLT tab shows up empty until you press Transform button, but that delay in UI is not very nice.  But I agree if you don't like the "default" output filename, and you want to change it then you end up with a lot of garbage files to clean up.  I suppose I could move the first file to the %TEMP% folder and auto-delete it when user is done with it...

**Comment by lovettchris** [comment]
I've decided not to change the current behavior for now.  Having  the HTML in the same folder allows it to find local html assets that are used inside the transformed output (images, javascript, css, etc).  So if you have a better design it will need to be spec'd out a bit more.
