### ISSUE TITLE
Save diff report

### ISSUE THREAD

**Issue by alecsandru95** [Microsoft/XmlNotepad#9]
Hi,

Can you add a save comparison report functionality?
Thanks

**Comment by lovettchris** [comment]
With the version 2.7.1.11 of XML notepad you will see it opens the diff output in a temporary html file (you will see something like this in your Web Browser address bar: file:///C:/Users/username/AppData/Local/Temp/ojvumhhn.htm).  This means the comparison is already saved in that temporary file, you could copy that to a more permanent location pretty easily using the windows file path: "C:\Users\username\AppData\Local\Temp\ojvumhhn.htm".
