### ISSUE TITLE
Switching between tabs "Tree View" and "XSL Output"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#92]
It seems that switching between tabs "Tree View" and "XSL Output" always transforms the output from scratch. For small files it is not important, but for monster files it takes a lot of time.
Maybe you can check if the existing output can be used or if it really needs to be recalculated?

**Comment by lovettchris** [comment]
Yeah, definitely could optimize that better.  Doing it or not is easy enough, based on whether you've modified or reloaded the XML document, but doing an incremental update is much harder since the xslt transform engine doesn't support such a concept.

**Comment by Pierre-de-la-Verre** [comment]
The XSLT has to be checked for modification too, right?
________________________________

**Comment by lovettchris** [comment]
Right and that part is already implemented.  It checks the file last modified time and reloads the XSLT if necessary.

**Comment by lovettchris** [comment]
Closing for now since what can be optimized is already.

**Comment by Pierre-de-la-Verre** [comment]
Do I see it right that the "... Button" to define the output does not invoke a "save as .." dialogue, but an "Open File " dialogue? Is it indented?
