### ISSUE TITLE
Suggestion: Use user-defined editor for "View - Source"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#93]
It would be fine to use a user-defined editor instead of Notepad with it limited functionality...

**Comment by lovettchris** [comment]
Added user option for custom text editor in version 2.8.0.32, like this:
![image](https://user-images.githubusercontent.com/18707114/119811435-eff5be00-be9b-11eb-859f-092f99fd037e.png)

**Comment by Pierre-de-la-Verre** [comment]
Suuuper cosmetics: The tooltip in the menu could be modified from "Notepad" to "selected editor"

**Comment by lovettchris** [comment]
Ah, thanks for pointing this out, it will be fixed in the next release.

**Comment by lovettchris** [comment]
Fix is in 2.8.0.33.

**Comment by Pierre-de-la-Verre** [comment]
I'm not searching for it, but by incident I found another place (and maybe not the last one) where "Notepad" is used:
![grafik](https://user-images.githubusercontent.com/13277944/121687468-ad023000-cac2-11eb-9c16-a6ef57b8adf0.png)

**Comment by lovettchris** [comment]
good catch, thanks.  That will be fixed in the next version.
