### ISSUE TITLE
Cosmetics in "Add schema"

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#94]
Cosmetic stuff ..

When I don't have a schema and click "Add schema", then the default for file-name is "openFileDialog1"
When there is already a schema, the path and name is displayed, but it runs partially out of the edit-field on the left side.

**Comment by clovett** [comment]
Good bug with the "openFileDialog1", but I think your second point you are just seeing normal text field horizontal scrolling when the path is too long to fit given the size of the dialog.  You can resize the dialog, or scroll the field using mouse selection, or arrow keys when the field has keyboard focus.

**Comment by lovettchris** [comment]
"openFileDialog1" fixed in version 2.8.0.32.

**Comment by Pierre-de-la-Verre** [comment]
It's not caused by long paths - see here with a short path:
https://autode.sk/3oTopbL

**Comment by lovettchris** [comment]
Ah I see what you mean now, thanks for the video.  Yeah, I have no idea why the file open dialog is doing that.  It seems to be selecting 15 characters of the path.  It is suspicious that this is the same length of the name of the dialog "openfiledialog1".  But have no control over this dialog which is provided by WinForms and Microsoft Windows... If you find a solution I'll be happy to fix it.

![image](https://user-images.githubusercontent.com/18707114/119891597-062c6a00-beee-11eb-8ba2-a2ea72cfaedf.png)

**Comment by Pierre-de-la-Verre** [comment]
_"openFileDialog1" fixed in version 2.8.0.32._
Does not work for me. If the list is completely empty and I select the first schema, I still get this string.

**Comment by lovettchris** [comment]
Fix is in 2.8.0.33.
