### ISSUE TITLE
😕 hmm?

### ISSUE THREAD

**Issue by iJahangard** [microsoft/XmlNotepad#96]
How much it takes time to replace icons with some modern icons like MS office?

**Comment by lovettchris** [comment]
Not long, know any good graphic artists?

**Comment by iJahangard** [comment]
Me 🙂

**Comment by iJahangard** [comment]
Do you want application icon too ?
To be more MS like :/
Give me a zip includes all icons that you want to make change in them

And tell me if you want them in svg(in case u want convert them xml) or png or ico format

**Comment by lovettchris** [comment]
Oh, sweet :-) The icons live here: https://github.com/microsoft/XmlNotepad/tree/master/src/XmlNotepad/Resources.  I think the xmlnote.ico is just for the desktop icon and I think that's ok for now.  But I'm excited you want to take a crack at updating them, feel free to also make them bigger and tell me what size they need to be etc.  I also want to fix the "dark" theme so it includes the whole window including the menus and toolbars.  So if you can design 2 sets of icons perhaps, one for light and one for dark theme, or is there a way to "process" the bitmap to work as light or dark, I think that's what VisualStudio is doing.  Anyway, awesome.  I probably should also flatten some of the rounded looking resizer bars, so it will look consistent with flatter metro style icons.  Maybe some things don't need to be in the toolbar, for example cut/copy/paste was removed from office toolbars long ago because everyone knows the shortcuts now...

**Comment by iJahangard** [comment]
I think deleting copy-cut-paste buttons is a good idea which make app less confusing and more clear 😂

I was thinking about some colorish icon but some flat icons will be good two and doesn't take to much time
I guess icons are 16by16 ,so make a little of gap will satisfy high display expensive
I guess 20 or 22 is good enough

I like help icon more than a help menu, but hey ! Who even need it 😅

So as you said , some part of app nee new color and feel like 
Tabs to be same size (action or non-active)
Divide lines to be just one pixel and more ligher or darker depend on which theme they are 

BTW bitmap is not good, should you use png or maybe xml , i think png or ico is good enough

If you know how to configure applications for dark mode, may I ask you bring dark mode for one of my favorite applications (which is free and open source) 
Almost 6 years with no update

**Comment by iJahangard** [comment]
Can you use aero glass effect or something in the app?

**Comment by lovettchris** [comment]
I prefer transparent .png images for the icons.  I hope to port the app to WPF one day and the icons will work nicely there as .png.  I like your other suggestions.  I'm not a huge fan of glass UI's.  I've noticed every time windows tries it they end up backing off.  The calculator is still slightly transparent, but only when it is the active app.  But I'd skip transparency for now.

**Comment by iJahangard** [comment]
> I prefer transparent .png images for the icons.  I hope to port the app to WPF one day and the icons will work nicely there as .png.  I like your other suggestions.  I'm not a huge fan of glass UI's.  I've noticed every time windows tries it they end up backing off.  The calculator is still slightly transparent, but only when it is the active app.  But I'd skip transparency for now.

You are right, using glassy effects were a bad experience but now in windows 10 it kinda ok as long as they use noises in the effect

Soooo. I will make some stuff
png format in black and white colors
And some colorish ones maybe 
in 20x20 pixel or you 16x16 and let you make the gaps fot it, think it's better

Let's finalize this issue🙃

**Comment by iJahangard** [comment]
Oh BTW can i see some results through using reshacker to apply icon and...?

**Comment by lovettchris** [comment]
Oh, let's go all the way to 32x32.  I think what's happening as screen resolutions and DPI continue to increase buttons are getting bigger and bigger so they can be easily hit.  So 32 gives me some UI options for big ribbon.  I can always provide a collapse ribbon option for folks who want them smaller again, and then I can just resize to the smaller size as needed.  

Sorry don't know what reshacker is, looks like a .ico editor.  I use Axialis Icon Workshop, but do you need me to export some .ico files as png's ?  I think the app icon is the only .ico I'm using and that can remain as is for now I think.

**Comment by iJahangard** [comment]
I didn't mean that, reshacker is an icon resources editor which in something case u can edit icons and pngs in some executed apps

**Comment by iJahangard** [comment]
BTW You know how to configure a wpf app to have a dark mode, right?
Can you help me in some problems?

**Comment by iJahangard** [comment]
https://mega.nz/file/3chShYwa#QCY-S8M5O1xJldF3uq1b9QocnTBx-yFNfA7PP9Orm2Y


Here is some changes! Includes a beautiful app icon in svg and ico

**Comment by iJahangard** [comment]
> yep, I usually start with this [Wpf App Template](https://github.com/clovett/tools/tree/master/WpfAppTemplate).  Sure I can help with problems.  If they are unrelated to this issue, you can email me at microsoft.com.  My email is first letter of first name followed by my last name, all one word.

Oh thanks , I will mail you about that sort of problems

**Comment by lovettchris** [comment]
Closing for now, the WPF refresh will change everything, not just the icons.
