### ISSUE TITLE
11 (un)install-entries?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [microsoft/XmlNotepad#99]
My "apps and features" in Win10 looks like this:
![grafik](https://user-images.githubusercontent.com/13277944/123925534-4bc7d100-d98b-11eb-93c5-4f27c0b79151.png)

Bug or feature?

**Comment by lovettchris** [comment]
Holy macaroons!  There are 3 installers on [this page](https://microsoft.github.io/XmlNotepad/#install/)(clickonce, standalone, winget) can you let me know which installer you've been using?

**Comment by Pierre-de-la-Verre** [comment]
Always the Standalone

**Comment by lovettchris** [comment]
Hmmm, ok, interesting, I'll have to do some research into how to fix that... in the meantime I assume you are just uninstalling all the ones you don't want...

**Comment by Pierre-de-la-Verre** [comment]
I think not the software is installed multiple times; there are only multiple deinstall entries. Heres from my other PC (with only 3 entries, created by „Uninstallview by Nirsoft“):

 

Anzeigename   Registry-Eintragsbezeichnung   Version                Registry-Datum               Installationsdatum         Installiert für                Installationsverzeichnis                Erstellzeit Installationsverz.        Änderungszeit Installationsverz.             Besitzer Installationsverz.             Herausgeber     Deinstallationsbefehl    Installationsänderungsbefehl   Befehl für stille Deinstallation                Bemerkungen  'Über'-Internetadresse                Programmversionsinfo-Internetadresse             Hilfe-Internetadresse                Installationsquelle          Installer-Name Ausgabeart        Programmsymbolpfad  MSI-Dateiname               Größe geschätzt            Attribute             Sprache               Gruppenschlüsselname               Registry-Schlüssel           

XmlNotepad      {BF28F2E3-95F5-49B7-9042-E00AEA94D457}       2.8.0.30                25.04.2021 23:16:23        25.04.2021          Alle Benutzer (32-Bit)            C:\Program Files (x86)\LovettSoftware\XmlNotepad    25.04.2021 23:16:22        30.06.2021 21:28:39                NT-AUTORITÄT\SYSTEM              Lovett Software              MsiExec.exe /X{BF28F2E3-95F5-49B7-9042-E00AEA94D457}                MsiExec.exe /X{BF28F2E3-95F5-49B7-9042-E00AEA94D457}       msiexec.exe /x {BF28F2E3-95F5-49B7-9042-E00AEA94D457} /qn                                                                      D:\Downloads\XmlNotepadSetup\        Windows Installer                           C:\Program Files (x86)\LovettSoftware\XmlNotepad\XmlNotepad.exe              C:\WINDOWS\Installer\4cd9a7.msi                11’277 KB            nicht änderbar, Windows Installer          en-US                   HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{BF28F2E3-95F5-49B7-9042-E00AEA94D457}         

XmlNotepad      {EE96CBA2-CC92-4D8A-9BE6-0037959A6F58}     2.8.0.31                19.05.2021 13:12:46        19.05.2021          Alle Benutzer (32-Bit)            C:\Program Files (x86)\LovettSoftware\XmlNotepad    25.04.2021 23:16:22        30.06.2021 21:28:39                NT-AUTORITÄT\SYSTEM              Lovett Software              MsiExec.exe /X{EE96CBA2-CC92-4D8A-9BE6-0037959A6F58}                MsiExec.exe /X{EE96CBA2-CC92-4D8A-9BE6-0037959A6F58}     msiexec.exe /x {EE96CBA2-CC92-4D8A-9BE6-0037959A6F58} /qn                                                                       D:\Downloads\XmlNotepadSetup(2)\  Windows Installer                           C:\Program Files (x86)\LovettSoftware\XmlNotepad\XmlNotepad.exe              C:\WINDOWS\Installer\56ac528.msi                11’177 KB            nicht änderbar, Windows Installer          en-US                   HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{EE96CBA2-CC92-4D8A-9BE6-0037959A6F58}             

XmlNotepad      {DB487366-AB85-4FFB-9EB1-E178C7CC4FAA}    2.8.0.35                30.06.2021 21:28:39        30.06.2021          Alle Benutzer (32-Bit)            C:\Program Files (x86)\LovettSoftware\XmlNotepad    25.04.2021 23:16:22        30.06.2021 21:28:39                NT-AUTORITÄT\SYSTEM              Lovett Software              MsiExec.exe /X{DB487366-AB85-4FFB-9EB1-E178C7CC4FAA}                MsiExec.exe /X{DB487366-AB85-4FFB-9EB1-E178C7CC4FAA}    msiexec.exe /x {DB487366-AB85-4FFB-9EB1-E178C7CC4FAA} /qn                                                                     D:\Daten\Privat\Konto_CH\XmlNotepadSetup\             Windows Installer                               C:\Program Files (x86)\LovettSoftware\XmlNotepad\XmlNotepad.exe                C:\WINDOWS\Installer\36ef71.msi        12’549 KB            nicht änderbar, Windows Installer          en-US                   HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{DB487366-AB85-4FFB-9EB1-E178C7CC4FAA}

**Comment by lovettchris** [comment]
I think I know what is going on.  Every time a build a new .msi for a new version of XML notepad it seems to install a new entry, instead of "upgrading" the version you have already installed.  The issue appears to be quite complicated, see [upgrading installers](https://wixtoolset.org/documentation/manual/v3/howtos/updates/major_upgrade.html) but I think I have something working.  You will have to uninstall all the duplicates, but the next updated .msi should "replace" the old version correctly.

**Comment by Pierre-de-la-Verre** [comment]
I "uninstalled" now all versions but the last, 0.35. Then I installed 0.38, and the list of installed programms seem to be OK and shows only 0.35

Thanks.
